src/main/web/florence/js/functions/_editDatasetVersion.js

Validate that CSDB file name matches dataset ID and that page has a dataset ID.
Add a CSDB file with a name that doesn't match the dataset ID and you should get a warning explaining what went wrong (without the file then being submitted). Also, remove the dataset ID from a dataset landing page, or find one without one, and then create a new version of the timeseries download and you should get another error message.
Anyone

Add warnings when uploading CSDB file with titling errors

---

src/main/web/florence/js/functions/_setupFlorence.js

Notify user when session is going to time out soon and gives opportunity to stop it from happening.
After 59 minutes and 30 seconds of inactivity notify will show.
Anyone

Give notification if session timing out

---

Jenkinsfile

Auto deploy to discovery on commit to dd-master branch.

Auto deploy to discovery on commit to dd-master branch.

---

.gitignore
src/main/web/florence/js/functions/_loadChartBuilder.js

Clicking the chart area when adding a plotline didn't move the plotline (see sandpit for a correct working version).
I've also squeezed a quick change to `.gitignore` file into this PR because it's so minor.
You can do the action described above.
Jon Jones

Fix annotation click

---

src/main/web/florence/index.html
src/main/web/florence/js/third-party/highcharts-annotations.js

The ability to drag an annotation to set it's co-ordinates had stopped working. Added in the other [annotations.js file from blacklabel](https://github.com/blacklabel/annotations) as well as the stock [highcharts module JS file](http://code.highcharts.com/5.0.7/modules/annotations.js).
Edit a chart and add an annotation. You should be able to drag this around the chart to set it's co-ordinates.
Jon or Rob.

Fix annotation drag in chart builder

---

src/main/web/florence/js/functions/_loadEmbedIframe.js
src/main/web/florence/js/functions/_loadMarkdownEditor.js
src/main/web/florence/templates/embedIframe.handlebars

Added functionality to allow choice of full width interactives
Add a interactive and test full width works
@Crispioso

Update functionality to allow choice of full width interactives

---

README.md

Add browse URL and setup credentials to README.md. There was no information about browsing to the login screen and which credentials to use.
Check the readme updates make sense.
@Crispioso @dave-Llew @robchamberspfc

Add browse URL and setup credentials to README.md

---

main.go
src/legacy/js/functions/_setupFlorence.js

- Add an extra route to handle a trailing slash on the default path to Florence
- Handle the default route in legacy Florence code so that it properly selects collections
A quick code review should be fine.
Anyone but me.

Handle trailing slash and add extra routes defaulting to collections

---

main.go

Fix importAPIURL assignment to actually work with env vars
Sanity check
Anyone but me

Fix var misassignment for import API

---

Dockerfile.concourse

Update docker file base image so that ca certs are included
No need, I paired with Lloyd on this change anyway.
Lloyd

Update docker file base image so that ca certs are included

---

src/app/components/file-upload/FileUpload.jsx
src/app/utilities/api-clients/collections.js
src/app/views/datasets/dataset-overview/DatasetOverviewController.jsx

Removed edition selector and changed button text to match UX
Added h2 tag to replace input label tag to match UX
Go to the upload page and verify changes
Anyone

Remove edition selector and update button text on upload screen

---

main.go
vendor/github.com/gorilla/websocket/AUTHORS
vendor/github.com/gorilla/websocket/LICENSE
vendor/github.com/gorilla/websocket/README.md
vendor/github.com/gorilla/websocket/client.go
vendor/github.com/gorilla/websocket/client_clone.go
vendor/github.com/gorilla/websocket/client_clone_legacy.go
vendor/github.com/gorilla/websocket/compression.go
vendor/github.com/gorilla/websocket/conn.go
vendor/github.com/gorilla/websocket/conn_read.go
vendor/github.com/gorilla/websocket/conn_read_legacy.go
vendor/github.com/gorilla/websocket/doc.go
vendor/github.com/gorilla/websocket/json.go
vendor/github.com/gorilla/websocket/mask.go
vendor/github.com/gorilla/websocket/mask_safe.go
vendor/github.com/gorilla/websocket/prepared.go
vendor/github.com/gorilla/websocket/server.go
vendor/github.com/gorilla/websocket/util.go
vendor/vendor.json

Updated the depedencies so the build no longer fails.
Check that the build has run successfully on Jenkins.
Anyone but me.

Add websocket dependency vendor and remove Mongo dependency to fix build

---

src/legacy/js/classes/_websocket.js

Handle websocket opening on secure and insecure networks.
Check that the websocket still opens correctly on load.
Anyone but me.

Handle websocket opening on secure and insecure networks

---

src/legacy/js/classes/_websocket.js

Apply limit to websocket retries.
A quick code check will be fine.
Anyone but me.

Apply limit to websocket retries

---

main.go

Correct env var for auth token to be consistent with other repos

---

main.go

Add auth token to import API requests 🥇

Add auth token to import API requests

---

src/app/utilities/api-clients/datasets.js

Removed published versions from displaying in the dataset list.
Check the above is true.
Anyone.

Removed published parameter from get request for instances

---

src/app/global/NavBar.jsx
src/app/utilities/api-clients/datasets.js
src/app/views/collections/details/CollectionDetails.jsx
src/app/views/datasets/DatasetsController.jsx
src/scss/components/_drawer.scss

Dataset tab now takes you to the dataset upload screen instead of dataset list screen.
Upload a dataset button has been removed from dataset lists screen.
Add dataset button added to collection details screen which takes you to the dataset list screen.
Check the above is ok.
Check that the collection ID is stored globally after clicking the add dataset button.
Anyone.

Collection to dataset journey updates

---

dist/css/main.css
dist/legacy-assets/js/main.js

Build assets

---

florence.nomad

* Configure the healthy threshold and deadline
* Enable auto rollback on failed deploy
* Set the stagger to a more appropriate value for a go app
Ensure configurations are valid and logical.
Anyone but me.

Improve nomad deployment resilience

---

florence.nomad

Allow for splitting the nomad classes.
Ensure the nomad class constraints are correct.
Anyone but me.

Allow for splitting the nomad classes

---

dist/css/main.css
dist/legacy-assets/js/main.js
dist/legacy-assets/js/templates.js
src/app/views/collections/CollectionsController.jsx
src/app/views/collections/CollectionsController.test.js
src/app/views/collections/details/CollectionDetails.jsx
src/scss/components/_loader.scss

Fix two issues with collections on approval:
1) The list of collections not updating with an 'in progress' state
2) The list of collections showing all collections, regardless of whether they were actually awaiting publish and not actionable.
A code check and create a collection, approve it and then collection should show as in progress (i.e. is has a grey bar next to it's name on the list) and then doesn't show in the list of collections list as well as the publishing queue once it's ready for publish.
Anyone but me.

Fix collections screen on approval (develop)

---

config/config.go
main.go

Don't send internal tokens to the import/dataset api
Verify logic is correct
Team B

Stop sending internal tokens from florence to import/dataset api

---

main_test.go
src/app/utilities/http-methods/request.test.js

Go file test and the Jest `request` test were failing.
Run `make test` and confirm it passes now.
Anyone.

Fix test failures

---

src/package.json

Attempt to fix the Jenkins build - Jest command to use direct path to executable
Check `test` command in package.json is correct.
Anyone but me.

Jest command to use direct path to executable

---

.travis.yml
src/app/views/collections/details/CollectionDetails.jsx

Update CMD dataset button in collection details to say 'Add imported dataset' instead of 'Add dataset'.
New text is correct.
Anyone but me.

Update dataset button text in collection

---

upload/upload.go
upload/upload_test.go

use filename in vault path to make it unique

use filename in vault path to make it unique

---

main.go

Set up new proxy for Babbage
@Crispioso

Set up new proxy for Babbage

---

policy.hcl

The vault policy injected into a dev environment was not updated with the new path format
Review changes
Anyone

Update vault policy for new path format

---

dist/css/app.css

Recompile assets and dist to remove committed merge conflict

Fix merge conflict

---

upload/upload_test.go

Fix unit tests (only create a psk if one doesn't already exist for that file)

Fix the unit tests

---

src/legacy/templates/workEditT16.handlebars

https://trello.com/c/3IPcbMNe/3259-move-prerelease-editor-to-bottom-of-list-1
1 - Create/edit
2 - on Home Create a Calendar entry
jon - crispin

prerelease button to the bottom

---

src/legacy/js/functions/_createWorkspace.js

remove uri in collection test on edit button which is causing false positives because 'data.json' is missing
deploy and test (not ideal)
@jondewijones

remove uri in collection test on edit button

---

dist/legacy-assets/js/main.js
src/legacy/js/functions/_editAddDataset.js

Remove comma from error message because it's really annoying that i forgot to remove it before
Remove comma from error message
Anyone

Remove comma from error message

---

README.md
USAGE.md

Added documentation on how to create content in Florence for devs to get setup quicker
(strictly happy path)
Check steps are accurate and descriptive
Anyone

Add basic usage docs to enable dev setup

---

src/app/views/datasets/metadata/DatasetMetadata.jsx
src/app/views/datasets/metadata/VersionMetadata.jsx
src/app/views/datasets/metadata/VersionMetadata.test.js
src/app/views/datasets/metadata/alert/AlertController.jsx
src/app/views/datasets/metadata/alert/AlertView.jsx
src/app/views/datasets/metadata/related-content/RelatedContentForm.jsx
src/app/views/datasets/metadata/usage-notes/UsageNotesController.jsx

- Added a 'Usage notes' input on the version metadata screen.
- Added a 'Next release date' input to the dataset metadata screen.
Check that both inputs work, are saved by the API and then rendered when the page is reloaded.
@jondewijones

Add new dataset inputs

---

src/app/views/collections/create/__snapshots__/CollectionCreateController.test.js.snap

Fixes some failing snapshot unit tests.
Ensure the npm tests are passing.
Anyone but @Crispioso or myself.

Fix failing snapshot tests

---

README.md

Updated the readme to be consistent with the app and it's config.
Check that the environment variables block is now correct.
Anyone.

Fix readme config

---

florence.nomad

Prevent florence from deploying on the mount node.
Ensure the nomad plan is valid.
Anyone but me.

Prevent florence from deploying on the mount node

---

dist/legacy-assets/js/main.js
src/legacy/js/functions/_setupFlorence.js

Re-comment out trim input whitespace function
Anyone

Re-comment out trim input whitespace function

---

README.md

add a verified commit

---

src/app/global/NavBar.test.js

Fix broken test suite
Run `npm test` and check all pass
Anyone

Add log mock

---

src/app/views/login/LoginController.jsx
src/app/views/login/LoginController.test.js

Upgrade Login page to use new log package
Anyone

Update logging package

---

src/app/views/users/UsersController.jsx
src/app/views/users/UsersController.test.js
src/app/views/users/change-password/ChangeUserPasswordController.jsx
src/app/views/users/change-password/ChangeUserPasswordController.test.js
src/app/views/users/confirm-delete/ConfirmUserDeleteController.jsx
src/app/views/users/confirm-delete/ConfirmUserDeleteController.test.js
src/app/views/users/create/UsersCreateController.jsx
src/app/views/users/create/UsersCreateController.test.js
src/app/views/users/details/UserDetails.jsx
src/app/views/users/details/UserDetailsController.jsx
src/app/views/users/details/UserDetailsController.test.js

added logging to users screen
open chrome developer tools Network tab
websocket Frames
Create/delete users
logs successfully created/deleted users
jon

logging in users screen

---

dist/css/app.css
dist/css/tablebuilder.css
src/scss/elements/_inputs.scss
src/scss/main.scss

- Reduce opacity of radio inputs to prevent some browsers displaying them (see image below) 
Anyone

Fix default radio buttons showing in some browsers

---

src/app/views/uploads/dataset/DatasetUploadsController.jsx
src/app/views/uploads/dataset/upload-details/DatasetUploadDetails.jsx

On dataset page some times the submit button wouldn't appear when it should, as such gone back to old functionality of always showing it
Click datasets and the upload a new dataset, check functionality all works

Submit button on upload dataset now always shown

---

config/config.go
main.go
src/app/utilities/api-clients/datasets.js
src/app/views/datasets-new/DatasetsController.jsx
src/app/views/datasets-new/DatasetsController.test.js

Update select dataset page to use publishing dataset controller
- You'll need [dp-publishing-dataset-controller](https://github.com/ONSdigital/dp-publishing-dataset-controller).
- Test the 'Select a dataset page' i.e.`/florence/collections/<<collection_ID>>/datasets` in Florence
Anyone

Update select dataset page to use publishing dataset controller

---

src/legacy/js/functions/_externalLinkAccordionSection.js
src/legacy/js/functions/_relatedItemAccordionSection.js
src/legacy/templates/editorLinks.handlebars
src/legacy/templates/editorRelated.handlebars

Pass new label value to templates to give more descriptive headings. Some have been left as-is where there was no straightforward solution. They will need some extra work and should probably get looked at by UR/UX.
Check new labels match their respective parts on the website
Anyone

Update accordion labels inline with website

---

src/legacy/js/functions/_relatedItemAccordionSection.js
src/legacy/templates/editorRelated.handlebars

Add case for related data
Add fall back when no label given
Log in to Florence, edit a dataset. The 'related data' accordion should look/work as normal
Anyone

Fix related data accordion labels

---

src/legacy/js/functions/_relatedItemAccordionSection.js

Updated related publications label
Anyone

Update related publications label

---

ci/build.yml
ci/unit.yml

Add caching to build and tests
Anyone

Add caching to build and tests

---

src/app/views/datasets-new/edit-metadata/DatasetMetadata.jsx
src/app/views/datasets-new/edit-metadata/DatasetMetadataController.jsx
src/legacy/package-lock.json

- These buttons now navigate back to the collections screen with the current collection selected.
- A second issue was discovered with the save and submit for review button not appearing on first creating a collection. This has been fixed and is now present.
1. Create a new version of a dataset. Check that the Save and Submit for Review button is present.
2. Click the save and submit for review button. You should be navigated back out  and to the collection screen. Note there is a timing soft spot here with async functions so it is worth checking that the version has indeed moved into the correct category.
3. Change user in Florence and navigate back into the collection and the dataset version.
4. Repeat step 2 but with an approval rather than a review.
Anyone except me.

Save for approval and save for submit fix

---

Makefile

Add npm-audit the make audit target
Anyone

Add npm-audit the make audit target

---

Makefile

Add change directory to find package.json
Anyone

Add change directory to find package.json

---

src/legacy/js/functions/_loadChartBuilder.js
src/legacy/templates/chartBuilderChart.handlebars

Remove colour options from chart builder
Anyone

Remove colour options from chart builder

---

service/service_test.go

Comment out test that was causing inconsistencies in test suites - passing sometimes and failing other times.
Sense check
Anyone

comment out brittle test

---

src/app/components/Select.jsx
src/app/global/PreviewNav.jsx
src/app/utilities/api-clients/content.js
src/app/views/preview/PreviewController.jsx

Fix visualisations in preview
- Upload a new visualisation so it is added to a collection
- View that collection as a "viewer" user type. You should be able to select the HTML files that make up the visualisation and preview them
Anyone

Fix visualisations in preview

---

service/service.go

updated path for upload service when registering a new route
Check if the path added are correct
Anyone

Changed path for upload service when registering a new route

---

src/app/views/homepage/edit/EditHomepageController.jsx

Increase the maximum number of entries for In Focus content. This enables content teams to add more to the homepage
Ensure change from 4 => 8 and tests pass
Anyone

update maximum number of entries for In Focus editing section

---

src/app/global/NavBar.jsx
src/app/views/collections/details/CollectionDetailsController.jsx

The "working on" tab appears outside of the collections route when it shouldn't be.
Anyone

Fix "working on" tab appearing when it shouldn't

---

main.go

Log config on start up 
Anyone

Log config on start up

---

USAGE.md

- Add additional detail for tracking the CMD import process
- Add reference to the import process sequence diagram
Check the changes make sense. Consider if anything more should be added.
Anyone

Add additional detail for tracking the CMD import process

---

src/legacy/js/functions/_viewPublishDetails.js
src/legacy/templates/publishDetails.handlebars

Add preview button publishing queue collection details pane
Test button navigates to preview and that preview is fully functional
Anyone

Add preview button publishing queue collection details pane

---

src/legacy/js/functions/_loadImageBuilder.js
src/legacy/package-lock.json
src/package-lock.json

Images often lack alt text on images for screen readers. Added validation for users to enter alt text. 
Go to content in Florence, try to save an image without alt text and see there is no validation message. Pull this branch and try to save an image and receive a validation message to enter alt text. 
Anyone but me.

add validation for alt text on images

---

src/app/views/datasets-new/create/CreateDatasetController.jsx
src/app/views/datasets-new/create/CreateDatasetController.test.js

Update create dataset page to use /dataset-controller/datasets. Was previously going directly to the dataset API. This is causing a bug since the introduction of pagination.
Review code / tests
If you want to integration tests, be sure to pull the latest changes in the dp-publishing-dataset-controller
Anyone (Jon :trollface: )

Update create dataset page to use /dataset-controller/datasets

---

src/app/views/homepage/edit/EditHomepageItem.jsx

Remove hostname mapping hacky fix for localhost vs 127.0.0.1. 
Reverts this commit: https://github.com/ONSdigital/florence/commit/9652a37d2f6996a1ec893a87563ca420f05b738f#diff-11c136ca0c8eb1cb27c4c1cd2b51d7e042218e920d1cdc1e9f3512f434f3e801
Anyone

Remove hostname mapping hacky fix

---

src/legacy/templates/chartBuilderChart.handlebars

- Update chart palette options. Remove extended
Anyone

Update chart palette options. Remove extended

---

src/app/utilities/api-clients/recipes.js

-append ?limit query param to /recipes call now that the API has pagination
Anyone

Release 1.27.0

---

src/legacy/templates/publishDetails.handlebars

Improve error message for publishing queue having too many files.
Check the code changes.
Anyone with florence understanding.

Update error message for publishing queue having too many files.

---

Makefile
src/audit-allowlist.json
src/legacy/package-lock.json
src/legacy/package.json

Updated `handlebars` and `node-sass `which had a dependency on `yargs-parser` which was failing the security audit. Also updated `make audit` to check the dependencies in the legacy folder
Pull branch and run `make audit`. Run Florence locally to ensure that css is still working as expected.
Anyone

Updated dependency vulnerability

---

src/app/utilities/api-clients/datasets.js
src/app/views/datasets-new/editions/DatasetEditionsController.jsx
src/app/views/datasets-new/editions/DatasetEditionsController.test.js

Use controller for editions list screen
Anyone

Use controller for editions list screen

---

src/legacy/js/functions/_editAddDataset.js

User made a publishing support request due to an error appearing and was unsure why it was appearing. This PR makes it clear why the error is being thrown and should enable the user to realise what they need to do to resolve the issue. Without dev support.
New error:
Check that only the error message has changed. Ensure that the Error message is clear.

Make the failed upload of dataset title clearer

---

USAGE.md
src/app/global/NavBar.jsx
src/app/utilities/http-methods/request.js
src/app/views/login/LoginController.jsx
src/app/views/login/LoginController.test.js
src/app/views/login/LoginForm.jsx
src/app/views/login/SignInController.test.js
src/app/views/login/SignInForm.jsx
src/legacy/js/functions/_handleApiError.js
src/legacy/templates/login.handlebars
src/legacy/templates/mainNav.handlebars

From a users perspective
- Login/Log in replaced with Sign in
- Logout/Log out replaced with Sign out
- URL to remain as Login
Content Design has requested as part of the new Auth work we change login terminology with sign in terminology. 
Tech lead decision was to only change the users perspective of the wording and not to roll the change out around the codebase (e.g. comments, functions etc) and to exclude the URL/Endpoints from this work.
Check that all instances of Login/Logout from a users perspective have been changed and spelt correctly in each place. Ensure that wording of errors still make semantic sense.
Some areas to look out for:
- Nav bar
- Login screen
- Error messages

Login replaced with Sign in

---

Makefile
config/config.go
config/config_test.go
go.sum
service/handlers_test.go
src/app/components/Input.jsx
src/app/config/initialState.js
src/app/config/reducer.js
src/app/utilities/api-clients/datasets.js
src/app/views/datasets-new/editions/DatasetEditionsController.jsx
src/app/views/datasets-new/editions/DatasetEditionsController.test.js
src/app/views/datasets-new/versions/DatasetVersionsController.jsx
src/app/views/datasets-new/versions/DatasetVersionsController.test.js
src/app/views/homepage/edit/EditHomepageItem.jsx
src/app/views/homepage/edit/EditHomepageItem.test.js
src/app/views/login/LoginForm.jsx
src/app/views/login/SignInController.jsx
src/app/views/login/SignInController.test.js
src/app/views/login/SignInForm.jsx
src/audit-allowlist.json
src/index.js
src/legacy/js/functions/_editAddDataset.js
src/legacy/js/functions/_setupFlorence.js
src/legacy/package-lock.json
src/legacy/package.json
src/package-lock.json
src/scss/base/_typography.scss
src/scss/base/_utilities.scss
src/scss/elements/_inputs.scss

Check that all work has been signed off
Check that nothing has slipped into this release that shouldn't be in here

Release 1.29.0

---

USAGE.md
src/app/global/NavBar.jsx
src/app/utilities/http-methods/request.js
src/app/views/login/LoginController.jsx
src/app/views/login/LoginController.test.js
src/app/views/login/LoginForm.jsx
src/app/views/login/SignInController.test.js
src/app/views/login/SignInForm.jsx
src/legacy/js/functions/_handleApiError.js
src/legacy/templates/login.handlebars
src/legacy/templates/mainNav.handlebars

- Ensure all work in this release has been 'sign'-ed off
- Ensure nothing has slipped into the release that shouldn't be here

Release 1.30.0

---

src/package-lock.json

Audit was failing, so ran npm audit fix in both src/ and src/app to update dependencies and hopefully resolve security issues

npm audit fix run in both src/ and src/app

---

service/directors.go
service/directors_test.go
service/service.go
src/app/config/reducer.js
src/app/utilities/api-clients/user.js
src/app/utilities/http-methods/request.js
src/app/utilities/http.js
src/package-lock.json

- Check nothing has slipped into this release that shouldn't be in it
- Ensure that all work has been signed off

Release 1.33.0

---

service/service.go
src/app/utilities/cookies.js
src/app/utilities/cookies.test.js
src/app/utilities/errorCodes.js
src/app/views/forgotten-password/forgottenPasswordController.jsx
src/app/views/forgotten-password/forgottenPasswordEmailSent.jsx
src/app/views/forgotten-password/forgottenPasswordRequest.jsx
src/app/views/login/SignInController.jsx
src/index.js

Part of the work to replace Zebedee user Auth with Cognito Auth.
User now has the ability to request a password reset. This PR creates the Forgotten password page. Note that conformation will live on the same page and will be built in an upcoming task.
- Pull florence
- Run make node-modules
- Run Florence with the following feature flag ENABLE_NEW_SIGN_IN=true
- Go to /florence/login
- Click the Forgotten your password? link
- You should be redirected to /florence/forgotten-password
- Try entering some bad formatted email addresses e.g. something@somewhere, you should get errors saying invalid.
- Try entering a valid formatted email something@somewhere.com You should then see a new page which isn't yet constructed - this is in a ticket coming to you soon.

Forgotten password request reset screen

---

src/app/components/panel/Panel.jsx
src/app/utilities/errorCodes.js
src/app/views/change-password/changePasswordConfirmed.jsx
src/app/views/forgotten-password/forgottenPasswordController.jsx
src/app/views/forgotten-password/forgottenPasswordController.test.js
src/app/views/forgotten-password/forgottenPasswordEmailSent.jsx
src/app/views/forgotten-password/forgottenPasswordRequest.jsx
src/app/views/login/SignInController.jsx
src/app/views/login/SignInController.test.js
src/app/views/login/SignInForm.jsx
src/scss/base/_variables.scss

Release 1.37.0
- Forgotten password screen complete
- Tidy up
- lets to const
- Change numerous JSX  `={"x"}` to `="x"` for performance gains
- Fixed spelling of `heading`
- Fixed misuse of Panel component

Release 1.37.0

---

src/app/config/reducer.js

That should have need added to my last PR. I created separate state for user and moved those actions there too so this is not needed anymore.  https://github.com/ONSdigital/florence/tree/develop/src/app/config/user 
frontend devs

fix: remove redundant actions

---

src/app/views/collections/CollectionsController.jsx
src/app/views/collections/create/CollectionCreate.jsx
src/app/views/collections/create/CollectionCreateController.jsx
src/app/views/collections/create/__snapshots__/CollectionCreateController.test.js.snap
src/app/views/users/change-password/ChangeUserPasswordController.test.js

It was reported to us the users doesn't get proper form validation on name.  
Acceptance Criteria: `They system checks that the Collection name does not already exist before creating the collection (rather than creating the collection before checking the existence of the collection name)` 
Ticket: [Resolve Collection Creation Error Message](https://trello.com/c/urvOoUjO/563-resolve-collection-creation-error-message)
Users reported that even unique names are reported to be 'taken'. I wasn't able to verify it. 
Check the code if doesn't contain any logical errors and meet the coding standards. 
Front end dev

feature: Resolve Collection Creation Error Message

---

src/app/views/collections/CollectionsController.jsx
src/app/views/collections/create/CollectionCreate.jsx
src/app/views/collections/create/CollectionCreateController.jsx
src/app/views/collections/create/__snapshots__/CollectionCreateController.test.js.snap
src/app/views/users/change-password/ChangeUserPasswordController.test.js

1. [feature: Resolve Collection Creation Error Message](https://trello.com/c/urvOoUjO/563-resolve-collection-creation-error-message)
check if tickets included in this release are signed off
anyone

Release 1.47.0 

---

src/app/components/text-area/TextArea.jsx
src/app/components/text-area/__snapshots__/textArea.test.js.snap
src/app/components/text-area/textArea.test.js
src/app/views/login/SignIn.jsx

There is already a text area component buried in the `<Input>` component but it doesn't quite meet the needs of the new Auth screens in addition it doesn't meet the new UX for the component. Because of this, we would need to make quite a few adaptations and add more options to it. The `<Input>` component which is the container for the current textarea component is already a bit of a monolithic component. 
I don't think `<Input>` should be handling HTML textarea as well as HTML input as this is what is causing the convoluted mess in the component. As such this PR introduces a clean new text area component that can meet the new UX designs without breaking current text areas in play.
At some point, a small addition to the session management work had been accidentally dropped. This adds it …

New component TextArea

---

src/app/utilities/api-clients/user.js
src/index.js

Correct error in the feature flag handling on new User list page
Check the enableNewSignIn flag does not have a `!` in front of it on user.js line 17 and index.js line 146.
Anyone but me

remove 'not' that was used in testing

---

src/app/constants/Errors.js
src/app/views/collections/edit/CollectionEditController.jsx

This is missing part merged before in https://github.com/ONSdigital/florence/pull/634 
The validation should only happen when there is actually a change in name, and should not stop saving other changes 
Front end

bug:  Edit collection

---

src/app/components/Select.jsx
src/app/components/banner/Banner.jsx
src/app/components/banner/Form.jsx
src/app/components/banner/index.jsx
src/app/components/simple-editable-list/SimpleEditableList.jsx
src/app/hooks/useInput.js
src/app/views/collections/details/CollectionDetailsController.jsx
src/app/views/homepage/edit/EditHomepage.jsx
src/app/views/homepage/edit/EditHomepageController.jsx
src/app/views/homepage/edit/EditHomepageItem.jsx
src/scss/components/_banner.scss
src/scss/main.scss

[Feature: Add ability to publish a 'site-wide' banner across the website banner](https://trello.com/c/rmrK67hM/679-as-a-publishing-user-i-want-the-capability-to-publish-a-site-wide-banner-across-the-website-header-nav-so-that-for-certain-scena)
This is urgent request so the component doesn't have any validation at, and some elements need refactoring. Will add this once this is merged to develop for testing
sanity check
all dev

feature: Add ability to save and edit site wide emergency banner

---

src/app/components/Select.jsx
src/app/components/banner/Banner.jsx
src/app/components/banner/Form.jsx
src/app/views/collections/Collections.jsx
src/app/views/homepage/edit/EditHomepage.jsx
src/app/views/homepage/edit/EditHomepageController.jsx

some linting changes and sanity checks on default values 
sanity check
all devs

fix: make a check if default is available

---

src/app/views/datasets-new/create/CreateCantabularDatasetController.jsx
src/app/views/datasets-new/create/CreateCantabularDatasetController.test.js

@ symbol is required on the child props of `is_based_on`
Sense check
Tests pass
!me

Fix/amending json object props to include @

---

config/config.go
config/config_test.go
service/handlers_test.go
service/service.go
src/app/config/initialState.js
src/app/config/reducer.js
src/app/config/store.test.js
src/app/views/collections/details/CollectionDetails.jsx
src/app/views/collections/details/CollectionDetailsController.jsx
src/app/views/collections/details/CollectionDetailsController.test.js
src/legacy/js/functions/_setupFlorence.js

Remove the ENABLE_HOMEPAGE_PUBLISHING flag
Also added missing test in the handler checking the ENABLE_NEW_SIGN_IN can change to true
Check code and ensure there is no reference to the flag and tests pass
Anyone

Remove ENABLE_HOMEPAGE_PUBLISHING feature flag

---

src/legacy/templates/tags.handlebars

Added width style

---

src/legacy/js/functions/_t4ArticleEditor.js

Fixed bug where save broke if topics widget was empty

---

src/app/views/collections/create/CreateNewCollection.jsx

Fix for calendar entry input when creating new collection which got broken during refactor. 
Devs

fix: calendar entry schedule

---

src/app/components/simple-selectable-list/SimpleSelectableList.jsx
src/app/components/simple-selectable-list/SimpleSelectableListItem.jsx
src/app/components/table/Row.jsx
src/app/config/selectors.js
src/app/utilities/formatDateString.js
src/app/utilities/tests/mockData.js
src/app/views/collections/create/index.jsx
src/app/views/groups/Groups.jsx
src/app/views/groups/Groups.test.jsx
src/app/views/groups/__snapshots__/Groups.test.jsx.snap
src/app/views/groups/delete/Delete.jsx
src/app/views/groups/edit/EditGroup.jsx
src/app/views/groups/edit/__snapshots__/EditGroup.test.jsx.snap
src/app/views/groups/index.jsx
src/app/views/groups/members/index.jsx
src/app/views/users/create/CreateUser.jsx
src/app/views/users/create/__snapshots__/CreateUser.test.jsx.snap
src/app/views/users/edit/EditUser.jsx
src/app/views/users/edit/__snapshots__/EditUser.test.jsx.snap
src/app/views/users/groups/AddGroupsToUser.jsx
src/app/views/users/groups/AddGroupsToUser.test.jsx
src/app/views/users/groups/UserGroupsList.jsx
src/app/views/users/groups/__snapshots__/AddGroupsToUser.test.jsx.snap
src/scss/components/_table.scss
src/scss/elements/_forms-and-labels.scss

[Ticket: #902: Review usages of groups endpoints by florence](https://trello.com/b/C6NSsVaS/team-404-sprint-board)
No changes to functionality, code update and refactor to align with api.
Check code for logical flaws and reach out for demo if you want to see it in action. 

#902 - Correct group properties as per changes in backend and refactor code

---

src/app/reducers/interactives.js
src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesIndex.jsx
src/app/views/interactives/InteractivesIndex.test.js

showing title instead of label of each interactive on the index
Access interactive index page
anyone

Interactives index: Show title instead label

---

src/app/views/interactives/InteractivesIndex.jsx
src/app/views/interactives/InteractivesIndex.test.js

added ability to have multiple tags per index
upload an interactive and if it has various states it will display what is returned from the api
anyone

Multiple tags on interactives index

---

src/app/views/interactives/InteractivesIndex.jsx
src/app/views/interactives/InteractivesIndex.test.js

fixing tag styling
access interactives index
anyone

Interactives index tag stylefix

---

src/app/views/interactives/InteractivesIndex.jsx

updated option text from latest publish to last updated
Access interactives index and try to sort using the filter
anyone

Interactives index: sort by Update option text

---

src/app/views/interactives/InteractivesForm.jsx

amended endpoint of api, to match preview 
look at the preview page on an edit interactive screen
anyone

interactive preview: Rename update to interactive

---

src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesForm.test.js

added /embed for the human slug url
access edit screen of interactives
anyone

interactives edit screen: Complete url for slug

---

src/app/components/layout/Layout.jsx
src/app/config/user/userHooks.js
src/app/utilities/api-clients/user.js
src/app/views/login/LoginForm.jsx
src/app/views/login/SignIn.jsx
src/app/views/login/SignIn.test.js

Reverts back to existing login code to fix broken authentication
reverted all the changes i made to the layout and sign in components
pull the code down and run with your flags and make command
anyone
myself

fix login for legacy users

---

src/app/reducers/interactives.js
src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesForm.test.js
src/scss/components/_alert.scss
src/scss/views/_interactives.scss

Connected to the api endpoints to be able to validate each field as a standalone
try to upload a new interactive and purposely miss out one or multiple fields. Or edit existing interactive and remove content and try to save changes/update
anyone

Interactives validations

---

src/app/components/layout/Layout.jsx
src/app/config/user/userHooks.js
src/app/utilities/api-clients/user.js
src/app/views/login/SignIn.jsx
src/app/views/login/SignIn.test.js

re fix refresh bug

---

src/app/views/content/CreateContent.jsx
src/app/views/content/CreateContent.test.js
src/setupJest.js

put 4th type behind the flag 
turn the flag on and off and see which features are enabled
anyone

Show enabled modules only

---

src/app/utilities/auth.js
src/index.js

Fixes authentication for when the redux store hasn't received the latest state of the logged in user.
This is a quick fix to help devs continue to work on the app with existing authentication (with the `auth_token` unsecure cookie, with the new authentication / secure http cookie this should not be an issue.
Run with your feature flags & check this doesn't cause any regression
Navigate around the part of the app you're working on and check your authentication does not restrict access if authenticated  successfully.
anyone
myself

fixes auth for all users

---

src/app/views/interactives/InteractivesDelete.jsx
src/app/views/interactives/InteractivesDelete.test.js

updated delete view to have dynamic content instead of placeholders
find an interactive on the index screen, press delete and then observe
anyone

Interactives: Update delete view

---

src/app/components/layout/Layout.jsx
src/app/utilities/api-clients/user.js

remove error flash message
This removes an a layout component error flash message that is obsolete & causing issues for other devs
pull code down and run with & without feature flags
pull code down and run with & without feature flags
myself
anyone

Removes error flash msg

---

src/app/config/thunks.js

403 adding users to a group
corrected the request url 
check the url does not effect current world otherwise we need to wrap this in a ff
run florence with current and future worlds and create a group with users
anyone familiar with florence
myself

#904: Create team/group error trying to add members

---

src/app/views/login/SignIn.jsx

Florence Show password toggle not working
The state is checked against the next state.
Run florence with `ENABLE_NEW_SIGN_IN=true` 
Enter a password & click the "Show password" toggle button
florence devs
myself

#977: Florence: Shows password not working

---

src/app/views/interactives/InteractivesIndex.jsx

Amending filters selection of the interactives from the collection screen,
collections > create/edit > select interactives 
anyone

Interactives - filtering linked to collection & published

---

src/app/views/interactives/InteractivesDelete.jsx
src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesIndex.jsx
src/app/views/interactives/InteractivesShow.jsx

removing hero from all interactives screen
access all interactive screens
anyone

Interactives: removing hero

---

src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesIndex.jsx

Commit files touched by `prettier` in the postinstall
When running `make node-modules-react` on a fresh copy of the repository, `prettier` touches several files as part of the postinstall task. This leaves a dirty copy of the repository that cannot be updated without clearing out the changes.
- Run `make node-modules-react`
- Verify that no files tracked by git are changed
Anyone

Commit files touched by prettier in the postinstall

---

src/app/utilities/api-clients/collections.js
src/app/utilities/http-methods/request.js
src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesForm.test.js
src/app/views/interactives/InteractivesIndex.jsx
src/app/views/teams/team-create/CreateTeam.test.js

hook up to api endpoints to update collection and interactive link
collections > create/edit content > interactives > link
anyone

Interactives: link to collection updates and some publishing workflow work

---

src/app/components/Input.jsx
src/app/views/interactives/InteractivesIndex.jsx
src/scss/views/_interactives.scss

amended the interactives index filter section to match new designs
access interactives index screen
anyone

Interactives: Filter Clear input

---

src/app/views/collections/mapper/collectionMapper.js
src/scss/components/_page.scss

Add interactives to collecitonMapper:
```
"interactives": [
{
"id": "5ddb747e-9e5b-48f7-a312-f6316ff895b4",
"title": "title",
"state": "Complete",
"uri": "http://localhost:27300/interactives/label-wzCxQw12/embed",
"lastEditedBy": "mryan321@gmail.com",
"files": [
{
"name": "index.html",
"URI": "/interactives/label-wzCxQw12/index.html"
}
]
}
],
```
👀 
💻

Add interactives to collectionMapper

---

src/app/utilities/http-methods/request.js
src/app/views/interactives/InteractivesDelete.jsx
src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesForm.test.js
src/scss/views/_interactives.scss

publishing workflow
access collections, try to review link interactive, save for approval etc
anyone

Interactives: publishing workflow

---

src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesForm.test.js

uploading interactive with collection ID
collections, select collection, create/edit content/ select interactive, upload interactive
anyone

upload interactive with collection id

---

src/app/reducers/interactives.js
src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesIndex.jsx

link to collection error fixes
collections > link to an interactive
anyone

Interactives: link to collection api errors

---

src/app/views/interactives/InteractivesForm.jsx

fixing interactive id call errors
collections > interactives
anyone

Call api when interactive.id is present

---

src/app/views/interactives/InteractivesForm.jsx
src/app/views/preview/PreviewController.jsx

interactive collection preview
access collection preview and see if interactives are shown
anyone

Interactives: Show interactives page in dropdown

---

src/legacy/js/functions/_viewPublishDetails.js
src/legacy/templates/publishDetails.handlebars

created a queue for the publish review 
check publishing queue
anyone

Interactives: Publish review interactives in queue

---

src/app/views/preview/PreviewController.jsx

preview html files
collection > preview
anyone

Rename files key

---

src/legacy/templates/publishDetails.handlebars

collection > create edit content > pick content > check icon on right hand side
collection > create edit content > pick content > check icon on right hand side
anyone

Interactives: Update interactive icon

---

src/app/views/interactives/InteractivesForm.jsx

interactives upload helper text
access interactive upload screen
anyone

Update help message

---

src/app/components/preview-nav/PreviewNav.jsx
src/app/views/interactives/InteractivesIndex.jsx
src/app/views/interactives/InteractivesIndex.test.js
src/app/views/preview/PreviewController.jsx

changing link of collections index
link an interactive
anyone

Interactives: Redirects to collections index

---

src/app/views/interactives/InteractivesForm.jsx
src/app/views/interactives/InteractivesForm.test.js

remove delete button from preview screen - edit interactive
access edit interactive 
anyone

Remove delete an interactive button

---

src/app/views/interactives/InteractivesForm.jsx

changing state of interactive when reviewed
collections
anyone

interactives: change state of interactive 

---

src/app/views/collections/details/collectionDetailsErrorNotifications.js
src/scss/views/_interactives.scss

delete from collection error
delete an interactive from collection
anyone

Update "success" error

---

src/legacy/js/classes/florence.js
src/legacy/js/functions/_environment.js
src/legacy/scss/elements/_nav.scss
src/legacy/templates/mainNav.handlebars

in florence
we used to have a banner for `You're on develop env`
and this ensures we now get `You're on sandbox env`

put banner for sandbox (was just in develop or sandpit)

---

src/app/views/interactives/InteractivesForm.jsx
src/audit-allowlist.json
src/legacy/package-lock.json
src/package-lock.json
src/package.json

Downgrade handsontable
Newer version removes vulnerabilities but the table builder does
not behave as expected: it won't display the contextual menu on cells
Edit/create a table
Right click on a cell
Contextual menu should display
Anyone

Release 1.59.1

---

src/app/views/interactives/InteractivesForm.jsx

- copy only relative paths
- dont show dropdown for single interactive

copy url + single interactive

---

src/app/utilities/api-clients/__tests__/interactives.test.js
src/app/utilities/api-clients/interactives.js

updated axios parameters to have no limits
try to upload
upload an interactive

interactives: Update axios parameters

---

src/app/views/collections/details/CollectionDetails.jsx
src/app/views/collections/details/CollectionDetails.test.js
src/app/views/collections/mapper/collectionMapper.js

show last edited by info 
access collections > and click on content and interactive
anyone

Show last edited by info

---

src/app/utilities/auth.js

publishers are experiencing problems not being able to create collections
hoping this will remedy
login as publisher and ensure can create a collection

possible fix for publisher/editor issue

---

src/app/config/reducer.js
src/app/config/selectors.js
src/app/views/collections/Collections.jsx
src/app/views/collections/create/CreateNewCollection.jsx
src/app/views/collections/details/CollectionDetailsController.jsx
src/app/views/collections/edit/CollectionEdit.jsx
src/app/views/collections/edit/CollectionEditController.jsx
src/app/views/collections/mapper/collectionMapper.js

Fixes collection group badges not displaying
Fixes groups not assigned to new collections on save
check the code and if in doubt ask me for a quick demo
anyone
myself

Fixes collection badges not displayed

---

src/app/config/reducer.js
src/app/config/thunks.js

handle bugfix user creation
access user creation page and enter details, then submit
anyone

Handle success and error response from createUser endpoint

---

src/app/config/groups/thunks.js

bugfix 3 , deleting user from a group
try to delete a user from a group
anyone

deleting user from group

---

src/app/views/login/SignIn.jsx

amended redirection to take to the last page 
access page
anyone

Redirect to query string

---

src/audit-allowlist.json

Was - Nothing, an empty-commit to trigger the CI/CD pipeline to grab the updated dp-table-builder-ui package.
Now - Had to add node-fetch to allowlist
Click approve.
Anyone.

PROD - Commit to get updated table builder

---

src/app/components/navbar/NavBar.jsx
src/legacy/templates/mainNav.handlebars

removing reports tab
check nav
anyone

removing reports tab

---

src/app/views/groups/edit/__snapshots__/EditGroup.test.jsx.snap
src/app/views/groups/members/Members.jsx

fixed group members with duplicate users
access group members and check for duplicate users
anyone

fixed group members with duplicate users

---

src/app/config/user/userHooks.js

fixing email link from blowing up
reset password, click on email link
anyone

Add reset password route to nonAuthRoutes

---

src/app/views/groups/edit/EditGroup.jsx
src/app/views/groups/edit/EditGroup.test.jsx

ability to change user's role
attempt to change user's role
anyone

ability to change user's role

---

src/app/views/groups/edit/EditGroup.jsx

ability to add admin to publisher role
Try to add admin to publisher role
anyone

ability to add admin to publisher role

---

src/app/views/collections/create/CreateNewCollection.jsx
src/app/views/collections/create/CreateNewCollection.test.js
src/app/views/collections/edit/CollectionEdit.jsx
src/app/views/collections/edit/CollectionEditController.jsx
src/app/views/groups/edit/EditGroup.jsx

Create a collection (incl. Adding a group for admin and publisher
try to create a collection

Create a collection (incl. Adding a group for admin and publisher

---

src/legacy/package-lock.json
src/package-lock.json
src/package.json

Downgraded handsontable due to complaints of the license key.
LGTM.
Anyone.

Downgraded handsontable

---

src/app/views/groups/edit/EditGroup.jsx

I have updated cognito with differing (not 10) precedence for special groups

use precedence of group to determine if special (e.g. admin)

---

ci/audit.yml
ci/build.yml
ci/lint.yml
ci/unit.yml

use tagged version of dockerfile with node 13
Anyone

use tagged version of dockerfile with node 13

---

src/legacy/js/functions/_t4ArticleEditor.js
src/legacy/js/functions/_tags.js
src/legacy/package-lock.json
src/legacy/templates/tags.handlebars
src/package-lock.json

Reworked topics functionality, subtopics can now be picked as topics, select now has groups, reworked string.
LGTM.
Anyone.

Topics Rework

---

src/app/views/collections/edit/CollectionEditController.jsx

added a wrap around permissions api call to prevent console error from being generated
added a wrap around permissions api call
anyone

added a wrap around permissions api call

---

src/app/config/user/userHooks.js
src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
src/app/views/datasets-new/edit-metadata/DatasetMetadataController.jsx

Fixes typo that was causing "What's changed?" field not to be saved in database.
Look at the code (and check the spelling :P)
Anyone

corrects latest typo

---

src/legacy/js/zebedee-api/_getPageData.js

Fix an error when reading Welsh dataset information if no English equivalent dataset exists
- Edit or create a Welsh dataset
- Download options > Add spreadsheet
- An error should not appear and the new period label show in the new element
Anyone

Send language to data endpoint

---

ci/audit.yml
ci/build.yml
ci/lint.yml
ci/unit.yml

use latest version of node-go docker image
anyone

use latest version of node-go docker image

---

src/legacy/js/functions/_t4ArticleEditor.js
src/legacy/js/functions/_t4BulletinEditor.js
src/legacy/js/functions/_t7MethodologyEditor.js
src/legacy/js/functions/_t7QmiEditor.js
src/legacy/js/functions/_t8LandingPageEditor.js
src/legacy/js/functions/_tags.js
src/legacy/package-lock.json
src/package-lock.json

Fix tagging across content types
Anyone

Fix tagging across content types

---

src/legacy/js/functions/_viewPublishDetails.js

- use 'publishDate' property not 'date'
Anyone

Fix missing 'publish' button on publishing queue details screen

---

src/app/utilities/sessionManagement.js
src/legacy/js/functions/_sessionManagement.js
src/legacy/package-lock.json
src/package.json

fix extending user session error
Ensure the code looks ok and the tests pass
!me

fix extending user session error

---

src/legacy/templates/editorAlert.handlebars

update alert editor title to 'Notices'
Anyone

update alert editor title to 'Notices'

---

src/app/views/collections/validation/collectionValidation.js
src/app/views/collections/validation/collectionValidation.test.js
src/legacy/package-lock.json
src/package-lock.json

Bug Fix for conditional due to id being compared to a string which was not converted to lower case.

---

src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.test.js

Changed the language to just be english regardless of the cookie set as per the request of the ticket. No other code has been touched to reduce cascading changes / issues. 
LGTM.
Anyone.

Removed code so the language defaults to english

---

src/package-lock.json
src/package.json

bump dp-table-builder to version 1.1.2
Anyone

bump dp-table-builder to version 1.1.2

---

README.md
service/modifiers/identity.go

this is an early clear-the-campsite PR before I add my actual feature
so they are bitesize PRs 🙏

tidy README; tiny bit of non-functional code tidying

---

ci/audit.yml
ci/build.yml
ci/lint.yml
ci/unit.yml

use docker image tag 1.21.7-bullseye-node-20
Anyone

use docker image tag 1.21.7-bullseye-node-20

---

service/modifiers/identity.go

Jira: https://trello.com/c/5UIlTLyT/2133-bug-auth-not-passed-through-to-publishing-subdomains
Added domain explicitly as it was not picking it up correctly.

Set domain to fix 401 error

---

src/app/components/navbar/NavBar.jsx
src/app/components/navbar/NavBar.test.js
src/app/views/users/UsersList.jsx
src/app/views/users/UsersList.test.js
src/app/views/users/edit/EditUser.jsx
src/app/views/users/edit/EditUser.test.jsx
src/app/views/users/edit/__snapshots__/EditUser.test.jsx.snap
src/app/views/users/edit/index.jsx
src/index.js

Allowed editors to access Users and Access screens in a read-only version. 
Switch on EnableNewSignIn - port forward 23200 to sandbox api router. 
Login as editor - check looks good
Login as admin - check looks good. 
Frontend react dev.

Allow read-only user screens to editors

---

src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadata.jsx
src/app/views/datasets-new/edit-metadata/DatasetMetadata.jsx
src/app/views/datasets/metadata/DatasetMetadata.jsx
src/legacy/templates/workEditT16.handlebars
src/legacy/templates/workEditT4Article.handlebars
src/legacy/templates/workEditT4ArticleDownload.handlebars
src/legacy/templates/workEditT4Bulletin.handlebars
src/legacy/templates/workEditT4Compendium.handlebars
src/legacy/templates/workEditT5.handlebars
src/legacy/templates/workEditT6.handlebars
src/legacy/templates/workEditT7.handlebars
src/legacy/templates/workEditT8Compendium.handlebars
src/legacy/templates/workEditT8LandingPage.handlebars

Update references to “National statistic” and “National statistics” to “Accredited official statistic” / “Accredited official statistics”.
Check changes ok.
Anyone

Update references of national statistics

---

src/app/components/chip/Chip.jsx
src/app/components/navbar/NavBar.jsx
src/app/views/groups/Groups.jsx
src/app/views/groups/Groups.test.jsx
src/app/views/groups/__snapshots__/Groups.test.jsx.snap
src/app/views/groups/edit/EditGroup.jsx
src/app/views/groups/edit/EditGroup.test.jsx
src/app/views/groups/edit/__snapshots__/EditGroup.test.jsx.snap
src/app/views/groups/edit/index.jsx
src/app/views/groups/index.jsx
src/app/views/groups/members/Members.jsx
src/index.js

Enable teams screen for publishing role
Log in as publisher role user and check can access "Preview teams" screen, screens work/match UX designs
Log in as admin role user check "Preview teams" screen works as before
Anyone

Enable teams screen for publishing role

---

src/audit-allowlist.json
src/legacy/package.json

add micromatch and braces vulnerabilities to allow-list
Anyone

Fix audit issues with release 1.75.0 - add vulnerabilities to allowlist 

---

src/app/utilities/api-clients/teams.js
src/app/utilities/api-clients/user.js

Add sorting to `GET` requests for groups, group members and users
Anyone

Add sorting for groups, group members and users

---

src/app/config/selectors.js

remove group sort function as we want sorted by name and this is now done by API
Pull changes. Test groups screen works and is in alphabetical order
Anyone

remove group sort function as we want sorted by name and this is now done by API

---

src/app/components/simple-selectable-list/SimpleSelectableListItem.jsx
src/app/views/content/CreateContent.jsx
src/app/views/groups/Groups.jsx
src/app/views/groups/__snapshots__/Groups.test.jsx.snap
src/app/views/users/UsersList.jsx
src/scss/components/_simple-select-list.scss
src/scss/elements/_buttons.scss
src/scss/elements/_inputs.scss

Design update to simple select list. Secauth and other pages that use it
Pull changes. Login and navigate to Users and Teams screens. See matches designs
Anyone

Design update to simple select list. Secauth and other pages that use it

---

florence.nomad

As per title.
No ONS libs have been updated.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.

Ensure deployments spread over availability zones

---

src/legacy/js/functions/_sessionManagement.js

Corrected more issues around the UI timeout in old Florence:
- more mismatches of BST vs UTC
- wasn't processing dp-identity-api response correctly on refresh
- some formatting fixes
Port forward to API router in publishing sandbox
Login to Florence
Go to old florence (old workspace)
Allow to hang for 30+ minutes
Should be able to continue to interact. Things you should notice:
- when you interact after the initial token expires (minus offset, so after 10 minutes), Florence will call the identity API and refresh the token and it should update the auth state held in local storage and the token should update. 
- expiry times held in localstorage are held as UTC times, not local time. 
- console log statements "[FLORENCE] Interval for sessionTimerPassive set to 600070" should be set when you …

Correct timeout issues in old Florence

---

src/app/views/collections/details/CollectionDetails.jsx

Fixed console error when loading edited by in the background. 
Run Florence with new auth switched on. 
Port forward API router address to sandbox. 
Browse collections for one with multiple entries. 
Click on one to open it's show hide
Currently it logs many console errors - now it doesn't. 
Florence dev.

Fix console error on loading with no lastEditedBy

---

service/modifiers/identity.go

Ensure cookies for domain are removed.
Check looks ok - didn't actually come up with a way of testing this locally. 
Florence dev.

Ensure cookies removed for domain

---

config/config.go
config/config_test.go
service/service.go

add wild card matching to proxy route handler
add '/data-admin' route to default url
Anyone

Data-admin proxy fix

---

Dockerfile.local
Makefile
README.md
ci/audit.yml
ci/build.yml
ci/component.yml
ci/lint.yml
ci/unit.yml
config/config.go
config/config_test.go
go.mod
go.sum
service/service.go
src/audit-allowlist.json
src/package-lock.json
src/package.json

- Remove wagtail proxy as not required. 
- Upgrade Go
- Separate audit tasks to allow individual running
- Upgrade x/crypto
- Upgrade babel packages
- Upgrade x/net
Check all traces of wagtail are removed.
Not me.

Remove wagtail proxy

---

service/service.go
src/app/components/generic-file-upload/GenericFileUploadContainer.jsx
src/app/views/uploads/dataset/upload-details/DatasetUploadDetails.jsx

Removed the Files API proxy
Check looks ok and tests pass. 
I don't know how to test it but it's also switched off in all environments and I believe last time it was switched on it didn't work. Questionable whether we should keep it there but I'm choosing to leave it there for now. 
Not me.

Remove files proxy

---

service/service.go
src/app/components/file-upload/bind.js
src/app/components/generic-file-upload/GenericFileUploadContainer.jsx
src/app/views/uploads/dataset/upload-details/DatasetUploadDetails.jsx

Remove upload and download service proxies
Check looks ok and that I got all of them - can optionally be tested for upload by:
- running florence
- port foward to sandbox api router
- upload homepage image
Not me.

Remove upload and download service proxies

---

service/service.go
src/app/utilities/api-clients/recipes.js
src/legacy/js/functions/_loadT8ApiLandingCreator.js

Deprecated the Recipe API proxy
Check looks ok, not missed anything
Not me.

Remove recipe API proxy

---

src/app/utilities/api-clients/datasetImport.js

Fixed import API Proxy path
Run Florence locally (make debug & make watch-src) 
Port forward to sandbox publishing
Login
Go to 'Datasets'
Select a Dataset.
Should now see an upload screen
Not me.

Fix import API proxy

---

service/service.go
src/app/utilities/api-clients/datasets.js

Deprecated the cantabular metadata extractor 
Check it's ok? 
Not me.

Deprecate Cantabular metadata explorer api

---

Dockerfile.local
ci/audit.yml
ci/build.yml
ci/component.yml
ci/lint.yml
ci/unit.yml

Upgrade node-go to 1.24.4
Check looks ok, tests pass.
Not me.

Upgrade to 1.24.4

---

src/app/views/login/SignInForm.jsx

Feedback from users says they go back to their link when their account is reset. Then it doesn't show the button on the UI. 
Check looks ok - should go to http://localhost:8081/florence/login?first-time=true and see the button still there when running florence (make debug)
Not me.

Reveal forgotten password even on first time

---

src/package-lock.json
src/package.json

Upgraded dis-authorisation-client-js to 1.0.1 - fixes bug related to fallback on no auth state.
Check looks ok. 
Optionally, to test:
- run Florence (make debug & make watch-src)
- port forward api router to sandbox
- login
- delete local auth state from session storage
- refresh page
- no error should occur
Not me.

Upgrade dis-authorisation-client-js

---

Makefile
README.md
ci/audit.yml
src/legacy/package.json
src/package.json

- Switch to vulncheck
- Add auth to OSS index checks for JS
Check tests pass, no code changes.
Not me.

Switch to vulncheck and add auth to OSS checks
