- src/main/web/florence/js/functions/_loadT4Creator.js
Bulletin creation failing because edition value being passed as argument to input validation, rather than jQuery selector.
Bulletins can be created easily.
Anyone but @Crispioso
> Fix bulletin passing value rather than selector to input validation

- src/main/web/florence/js/functions/_checkRenameUri.js
- src/main/web/florence/js/functions/_createWorkspace.js
Editing the title for a Welsh page would rename the path for both the English and Welsh version to the Welsh page's title. 
Welsh pages can be created at the same time as the English version being created and updating it's title doesn't update the path of the pages. It works correctly if you publish the English version first, so you can use that behaviour as an example of it working as expected.
@jondewijones
> Stop page rename on the edit of a Welsh page's title

- run.sh
Allow Florence's the port for the server-side application to be configurable by the environment.
Try and `./run.sh PORT=10000` and check whether Florence now starts up on port 10000.
Anyone but me.
> Add configurable environment variable for port to Java app

- src/main/web/florence/js/functions/_setupFlorence.js
Prevent 'new version' alert displaying when there's a Florence connection error
Probably needs to let the user know, e.g. using the network ping indicator or by greying out the screen
Start florence, open in browser, stop florence, make sure alert isn't displayed after around 10s
Anyone except @ian-kent
> don't display a version alert if there's a connection error

- src/main/web/florence/js/functions/_t6CompendiumDataEditor.js
Compendium data editor 'save' button didn't work - there was no response from clicking it. The save function was bound to the wrong ID.
Compendium data saves when the 'save' button is clicked.
Jon Jones
> Bind compendium data save to correct button class

- Makefile
- assets/prod.go
- main.go
Use `:8080` as default bind address but update to `:8081` in the `make debug` command, so that there's not a conflict during local development.
A simple code review of the file changes will be fine.
Anyone but me.
> Change default bind address to 8080 so it matches all other DP apps

- src/app/utilities/api-clients/datasets.js
- src/app/views/datasets/DatasetsController.jsx
- src/app/views/datasets/metadata/DatasetMetadata.test.js
- src/app/views/datasets/metadata/__snapshots__/DatasetDetails.test.js.snap
- src/app/views/datasets/metadata/__snapshots__/DatasetMetadata.test.js.snap
- src/app/views/datasets/preview/DatasetPreview.jsx
- src/app/views/datasets/preview/VersionPreview.jsx
- src/app/views/datasets/selectable-table/SelectableTableController.jsx
- src/app/views/uploads/dataset/upload-details/DatasetUploadMetadata.jsx
**Don't merge until https://github.com/ONSdigital/dp-dataset-api/pull/43 is merged.**
Update Florence to take advantage of the update to the Dataset API, which means we can make one request to get 'completed' and 'edition-confirmed' instances.
Current issue is that as soon as an edition is confirmed it disappears from the dataset screen.
1) Switch to the branch ~~`feature/state-filter-csv`~~ `cmd-develop` on the dataset API.
2) Make you have some instances that are a mix of the state 'completed' and 'edition-confirmed'.
3) Go to `/florence/datasets`.
4) Edition and version should for edition confirmed instances, but only edition for completed instances.
5) Clicking 'view' should take you to the correct respective url (e.g. a version goes to …
> Update datasets screen to handle completed and confirmed instances

- main.go
- src/legacy/js/classes/pathUtils.js
- src/legacy/js/functions/_setupFlorence.js
- src/legacy/js/functions/_viewController.js
Add the ability to go to a editor screen for a page via the URL alone. This will allow us to refactor the collections screen, because we needed the functionality to be able to keep the 'edit' click on a page item in a collection.
Check the code isn't too crazy (although a bit of leeway is needed because it's old Florence code) and check the functionality works. An example of what a working URL should look like:
```
/florence/workspace?collection=myCollectionID&uri=/economy
```
@jondewijones
> Routing to workspace edit screen

- src/app/views/datasets/DatasetsController.jsx
Allow the datasets screen to show the dataset ID if a title isn't in the object - prevents us from getting ugly runtime errors if they data isn't in the structure we expect.
Super quick code check should be fine.
Anyone but me.
> Show Dataset ID if title doesn't exist yet

- src/legacy/js/classes/_websocket.js
Remove logging of full websocket buffer because it causes an infinite loop - which we know will happen everytime at the moment because websockets aren't working on develop or production.
Code check.
Anyone but me.
> Stop logging full websocket buffer to fix infinite loop

- src/app/views/datasets/metadata/DatasetMetadata.jsx
Added some additional classes for the web acceptance tests for the dataset metadata page.
Checkout the dp-web-tests on the same branch (dataset-metadata-tests).
You can run just these tests using: 
`npm run start:chrome -- features/florence/datasets/dataset_metadata.feature`
Then check all tests pass
`./run.sh`
Anyone.
> Added classes for dataset metadata acceptance tests

- src/legacy/js/functions/_viewCollections.js
Fix the bug where 'Submit and review' and other actions in the workspace would direct to the old collections screen.
So I've updated the `viewCollections` function to always redirect to the new collections screen, making sure the legacy collections screen never gets rendered. 
You don't need the CMD stack running for this, just Zebedee (on any develop/master branch) and Florence on this branch.
Check that submitting a page for review save it and then returns you to the active collection on the refactored collections screen.
Anyone but me.
> Fix some routes going to old Collections screen

- src/app/utilities/http-methods/request.js
A hotfix to allow http responses that do not have content types
> Allow responses that have no content type

- src/app/components/Input.jsx
- src/app/utilities/api-clients/datasets.js
- src/app/views/datasets/metadata/VersionMetadata.jsx
- src/app/views/datasets/metadata/__snapshots__/VersionMetadata.test.js.snap
On load of the version metadata page, if the user is looking at an instance, the dimension label and description inputs are autopopulated from that latest published version.
There's also the options to fill them at any point from the latest published version (by clicking a button next to the form)
1) Have a published dataset version with some description/s and labels for the dimensions.
2) Uplolad a new version of that dataset - when first opening it (as an instance) the dimension inputs should been autopopulated with the descriptions and labels from the published version.
3) For a version or an instance the 'Fill from latest version' wipes the input values and replaces them with those from the published version. These changes aren't saved until the user hits 'Save' though.
Anyone but me.
> Auto populate version dimension inputs

- src/app/views/datasets/metadata/VersionMetadata.jsx
- src/app/views/datasets/metadata/VersionMetadata.test.js
- src/app/views/datasets/metadata/alert/AlertController.jsx
- src/app/views/datasets/metadata/alert/AlertView.jsx
Made a separate version alert component so that it could have two changes:
- Use a date input for alert
- Increase size of description input
Check that you can add and edit an alert for a version. There are existing bugs where editing an alert, saving the version and refreshing will duplicate the alert you edited. This is a problem between the API not allowing editing of alerts and the client expecting that it does.
Anyone but me.
> Separate version alert component

- src/app/views/datasets/metadata/VersionMetadata.jsx
- src/app/views/datasets/metadata/alert/AlertController.jsx
- src/app/views/datasets/metadata/alert/AlertView.jsx
Allow a user to toggle an alert to be a correction or not.
Also a fix for the description disappearing if an existing alert is opened and then saved without editing the description.
In a version of a dataset add/edit an alert. You should have a checkbox which you can check/uncheck, save and submit to the API - which then saves as `type: "correction"` in the data.
Anyone but me
> Alert: toggle correction

- src/legacy/js/functions/_createWorkspace.js
- src/legacy/js/functions/_handleApiError.js
- src/legacy/js/functions/_saveContent.js
Tell user which collection a URI is being edited in: 
* Use API response for generic saveContent errors
* Update handleApiError to display the `data` block returned by zebedee
* Check if file is in another collection when clicking the Edit button
* Use the `feature/find-collection-by-uri` branch of zebedee
* Edit URI in one collection and save, edit the same URI in another collection and you should get an error telling you it's in the first collection
* Create new URI in one collection, create the same URI again in another collection, you should get an error telling you it's in the first collection
Anyone except @ian-kent
> Tell user which collection a URI is being edited in

- src/app/views/collections/details/CollectionDetailsController.jsx
https://trello.com/c/pEtUUUwQ/3277-cancel-delete-doesnt-update-collection-deleteable-state
added "updatedActiveCollection.canBeDeleted = collectionMapper.collectionCanBeDeleted(updatedActiveCollection)" to CollectionDetailsController
Actions to recreate bug:
Create a collection (doesn't matter about it's name, publish type etc)
Click 'Create/edit page'
In browse tree of pages select a page (possibly something small like an 'About us' page)
Click in hamburger icon and select 'Delete'. The page should show as greyed out and crossed through. You've now selected this page to be deleted from the website.
Return to your collection in the collections screen. You should see the page you've deleted listed in the collection.
Note that at the bottom of the collection it should only have the 'Close' …
> Cancel delete updates collection state

- src/legacy/js/functions/_setupFlorence.js
Removed prompt for user to reload Florence when a new version has been deployed and they are on an older version
https://trello.com/c/oOILiXNd/3257-remove-new-version-of-florence-available-fuctionality-2
original Feature/version-reloading
https://github.com/ONSdigital/florence/pull/15
??? (no prompt in Florence)
jon - crispin
> removed Feature/version-reloading

- src/legacy/js/functions/_createWorkspace.js
Reintroduce collection URI check when editing a page in Florence (added `/data.json` to the end if it isn't already present)
- Create collection 1, edit a page, save changes
- Create collection 2, edit the same page, should get an error specifying the collection name when clicking the Edit button
Anyone except @ian-kent
> Reintroduce collection URI check when editing a page in Florence

- florence.nomad
Restrict deployment to only non-mount instances to ensure the special mount instances are kept clear for the apps that require them.
Ensure the node pattern no longer matches the mount nodes.
Anyone but me.
> Restrict deployment to non-mount instances

- dist/legacy-assets/js/main.js
- src/legacy/js/functions/_setupFlorence.js
Remove whitespace trimming on old Florence to temporarily fix chart builder input. Currently chart builder will break if the first heading is white space, which is very common for charts because quite often it's only from the second column onwards that chart have a heading.
I have just disabled the whitespace trimming function in old Florence because this issue is stopping a chart being built for release tomorrow.
Check that code is commented out correctly.
Anyone.
> Remove whitespace trimming on old Florence

- src/app/views/datasets-new/edit-metadata/DatasetMetadataController.jsx
If the user attempted to edit version information and dataset information in the same save then only the last changes would be saved.
1. Checkout this branch 
2. Change either version meta information:
- releaseDate
- notices
- usageNotes
- latestChanges
3. Change the dataset meta information
- title
- summary
- keywords
- nationalStatistics
- license
- contactName
- contactEmail
- contactTelephone
- relatedDatasets
- relatedPublications
- relatedMethodologies
- relatedFrequency
- unitOfMeasure
- qmi
- nextReleaseDate
Or swap step 2 and 3 around, both work.
4. Click save
5. Reload the page
6. One should see all their changes, note previously only the dataset or version data would have changed - whichever was last updated.
> Fix for updating both versionMetadata and datasetMetadata in same save

- dist/legacy-assets/js/main.js
- src/legacy/js/functions/_editIntLinks.js
- src/package-lock.json
Static pages modal for external links is now passed in a title: true option. A previous update made the title appear only if it was told to. (Rather than at all times) this was given to most pages on BAU but one, static_page was missed. This has now been added
Create  a generic static page under about us section on florence. Add related link, select external link. Ensure title field appears, populate modal then save.
If no errors then this is a success.
> Hot fix for not being able to add external links to static_pages

- src/.eslintrc.json
- src/package-lock.json
- src/package.json
* Eslint rules now extend prettier formatter along with react/prettier rules.
* Eslinter updated
* Check linting and prettier don't conflict
* Ensure everything still builds as normal
1. Run npm install, to ensure the new dependencies are installed
2. Navigate to ./src
3. Run `npm run eslint-check`
4. Hopefully it should say no conflict
5. Try create a conflict in the .eslintrc file add "semi: "error""
6. Rerun step three - this time it should say there is a conflict
Member of the ONS DP JavaScript Guild / Frontend Guild
> Updated linter, no conflict with prettier

- go.mod
- go.sum
Includes dp-s3 fix enabling florence to communicate to aws
* Terraform plans need updating, [see here](https://github.com/ONSdigital/dp-setup/pull/752), once this has been merged in and terraform plan has been run to update permissions then this pr can be merged
* Check unit tests pass
* This is a fix for florence to start connecting to aws buckets
Anyone
> Update go dependencies

- src/app/views/datasets-new/editions/DatasetEditionsController.jsx
- src/app/views/datasets-new/editions/DatasetEditionsController.test.js
Updated the label on the Select an Edition page of the dataset publishing journey:
- Changed the link label text to display the edition name
- Removed "Edition: {edition}" text
- Restructured the editions object array in the DatasetEditionsController so that these changes would be reflected in the list component accordingly
**Before**
**After**
- Ensure code changes are valid
- Ensure no knock-on effect to other parts of Florence based on these changes. I had a look through parts of the Florence UI and ensured test suites pass, but it would be helpful to get eyes on those with more knowledge of the domain
Anyone but me
> Update labels on Select an Edition page

- src/app/views/teams/team-edit/TeamEditController.test.js
- src/legacy/package-lock.json
- src/legacy/package.json
- src/package-lock.json
- src/package.json
- Force latest version of `lodash-es` and `minimist`
- Update versions of `copy-webpack-plugin` and `css-loader`
- Run formatter on test file
- Test all build scripts and that Florence still works fine
- Test all other npm scripts e.g. test
Anyone
> Fix NPM vulnerabilities as of 2020-04-08

- src/legacy/templates/workEditT7.handlebars
Update the label in the Florence workspace for static pages from "Release date" to "Last updated".
I was intending to update the markup too, however the jQuery logic for the datepicker is tied to the ID being `releaseDate`, and it looks as though there would be knock-on effects for other aspects of the workspace if the datepicker was refactored. Owing to the time required to rework it, I felt such a group of changes is probably out of scope for this ticket.
Check code change makes sense
Anyone but me
> update static pages label: 'Release date' -> 'Last updated'

- src/app/views/workflow-preview/WorkflowPreview.jsx
- src/app/views/workflow-preview/WorkflowPreview.test.js
- src/index.js
Created a workflow preview component (name can change) that can work as preview for any content type (even datasets as i see that preview moving towards the design of this one) and set up to act as preview for the new homepage publishing journey for this PR.
You can access the page directly by going to `/collections/{collection_id}/homepage/preview`
Anyone
> Add workflow preview component

- src/app/views/homepage/edit/EditHomepageController.jsx
Updated the URI passed in the collection check argument from `/` to `/data.json` to ensure the correct file is being checked to see whether it's in the collection. The response logic in the callback has also been inverted to read a bit more easily
Check the changes make sense
Anyone
> Fix collection uri and response logic

- src/app/views/homepage/edit/EditHomepageItem.jsx
Add `image` to the `EditHomepageItem` props so that the property is stored when editing/adding a new homepage featured content entry
Check the image property persists when saving an edited homepage field
Anyone but me
> added image to the EditHomepageItems so image ID can persist

- src/app/components/simple-selectable-list/SimpleSelectableList.jsx
- src/app/components/simple-selectable-list/SimpleSelectableListItem.jsx
- src/app/views/collections/details/CollectionDetails.jsx
- src/app/views/collections/details/CollectionDetails.test.js
- src/app/views/content/CreateContent.jsx
- src/app/views/content/CreateContent.test.js
- src/index.js
- Added new create content journey
- Content creation buttons such as "create/edit page", "edit homepage" etc should be replace by new "Create/edit content" button
- New content create journey page should link correctly to content types. 
- Create/edit some workspace content and check it saves to collection correctly
- Edit homepage and check it saves to collection correctly
Anyone
> Add new create content journey

- src/package-lock.json
- src/package.json
Bump `dp-table-builder-ui` package: `1.0.20` => `1.1.0`
This update includes the column/row headers validation work for the table-builder. The validation rules applied should ensure table headings are more appropriate for accessibility
Pull changes, run `npm install dp-table-builder-ui` and test that the validation works locally.
You can access the table builder module by going to the old workspace in a collection and opening an article. Click to edit its contents so the markdown editor appears, and click on the table icon to open up the module.
Anyone
> update table-builder version

- src/app/utilities/api-clients/datasets.js
- src/package-lock.json
Using the dataset API response URL contains the `v1` prefix as it goes through the API router. Using this path causes the subsequent request to fail. Building the URL ensures that this doesn't happen, and it more consistent with the rest of the code.
This bug surfaced when trying to add a dataset to a collection. Once on the dataset metadata edit screen an error would show as the latest version could not be found. Looking at the URL that it's trying to use, you can see the `/v1` in the path: `http://localhost:8081/dataset/v1/datasets/cpih01/editions/time-series/versions/2`
Review changes - check that I haven't broken anything
Anyone familiar with the Florence JS code
> Build URL for the latest version instead of using API response URL

- src/legacy/js/functions/_loadEmbedIframe.js
- src/legacy/package.json
Babbage relies on full-width being the second argument and title being the third in the string. At the moment visulisation are being incorrectly saved on disk corrupting the title and not allowing the full-width usage. The longer this goes unfixed the more data fixes required.
1. Go into Florence
2. Create a new article (or any page type that accepts vis content)
3. Edit the content section and then click add visualisation
4. Go to the ONS website and find an article that has a visualisation on it.
5. append the URL with /data
6. Search the JSON for the visualisation
7. copy the URL of it
8. go back to Florence and under the URL field for the visualisation paste the copied URL
9. tick the box 'make full-width'
10. continue to publish the content
11. Go to the content locally via web
12. …
> Data visualisations were saving title in the wrong order

- src/legacy/js/functions/_viewPublishDetails.js
- src/legacy/templates/publishDetails.handlebars
Wait for all requests to complete even if there's failures. Capture fails and present them back to user
- Check the publishing queues works as normal when no errors
- When there are errors the publishing queue should continue with work with the error collection accordion displaying the error and others working as normal
To simulate requests error you can edit the `getCollectionDetails` function so that certain errors fail. E.g. on a certain collection ID change the url so it will 404
Anyone
> Fix publishing queue collections details failures

- src/app/views/homepage/edit/EditHomepageItem.jsx
- src/package-lock.json
Before this, if an error happened during the file upload, then the upload button would disappear. I have reproduced this by blocking the PUT request to the images-API. Now when that happens, the button will reappear, and the user can try again.
However, I did note there is a second issue that prob should also be addressed.
If the user uploads an image, but the images-API is down, and the request therefore fails. Then a new image record is made behind the scene. However, it is going to be unsuccessful as to make a new record it needs to talk to the image-API. As a result, the 'state' is incorrect at this point. If the user stays on the screen and the image-API comes back up, then they will not be able to upload a new image on first attempt - where really there is no practical reason why …
> Buttons no longer disappear and on second retry it works

- src/app/views/datasets-new/edit-metadata/DatasetMetadataController.jsx
Set `disabledScreen` to `true` when we get an error calling getMetadata
- Stop running/don't start `dp-publishing-dataset-controller`
- Try edit CMD dataset version metadata e.g. `/florence/collections/{{collectionID}}/datasets/{{datasetID}}/editions/{{editionID}}/versions/{{versionNumber}}`
- The form should now be disabled (grey boxes) to prevent users editing content while Flo is in an error state
Anyone
> Set disabledScreen to true when we get an error calling getMetadata

- src/app/utilities/api-clients/recipes.js
`dp-recipe-api` recently had pagination implemented. This means on the "Upload a Dataset" page in Florence, only 20 datasets (default limit) is being displayed. This small PR ensures all datasets can be viewed on this page by adding a `limit` of 1000 (maximum limit as used in APIs). 
There will be further work down the line which will involve implementing a new pagination-specific pattern for this page, but as that will take some time to build, this quick fix will be in place for the time being
- Pull latest develop version of `dp-recipe-api` and run
- Run Florence with `ENABLE_DATASET_IMPORT=true` flag set
- Click on "Datasets" in the header and see that you should only see 20 datasets
- Change to this branch, run `npm run watch` in `/florence/src` and re-run the app. You should now see …
> Add limit query to recipes request

- src/legacy/js/functions/_loadBlockquoteBuilder.js
- src/legacy/js/functions/_loadMarkdownEditor.js
- src/legacy/scss/components/_markdown-editor.scss
- src/legacy/scss/partials/_workspace.scss
- src/legacy/templates/blockquoteBuilder.handlebars
- src/legacy/templates/markdownEditor.handlebars
This PR introduces a blockquote feature into the old workspace, so that the publishing team can create content that includes standout quotes.
- Sense check the code
- Pull latest Develop branch of Babbage. This includes the blockquote tag parser logic
- Pull this branch, run `npm install` and then make sure `npm run watch` is running. Both need to be run from the `/src` directory
- Create a collection, click "Create/edit content" and venture into the old workspace to an existing article page (or create one)
- Click on "Content" and then "Edit Content"
On the screen that pops up, the header should now include a blockquote button next to the paperclip (quotation marks icon):
Click that and you should see a new modal pop up that lets you enter a quote - the attribution field should be …
> first pass on implementing blockquote feature in old workspace

- go.sum
A dependency looks to have been removed added.
There seems to have been an attempt to readded it however it wasn't complete. This PR adds the indirect dependency go.sum entry back in.
The project will build without this dependency however if you were to run make debug then the project would fail to run. It would throw:
```bash
cd assets; go run github.com/jteeuwen/go-bindata/go-bindata -debug -o data.go -pkg assets ../dist/...
missing go.sum entry for module providing package github.com/jteeuwen/go-bindata/go-bindata; 
```
After running `go mod download github.com/jteeuwen/go-bindata` the go.sum entry is added and the project is runnable again.
Checkout this branch and run `make debug ENABLE_DATASET_IMPORT=true ENCRYPTION_DISABLED=true` Make sure to go to  `...:8081/florence/login` …
> Readded required go-bindata dependency

- src/app/views/homepage/edit/EditHomepageItem.jsx
- src/app/views/homepage/edit/EditHomepageItem.test.js
Remove input fields for alt text and image title since they are currently not used. 
Go into Florence, attempt to edit the homepage by clicking on "Add a headline". See that the bottom two inputs on the modal are Image title and Alt text. Pull this branch and see the inputs are gone. 
Anyone but me.
> remove alt text and image title inputs

- src/legacy/templates/chartEditBarlineExtras.handlebars
Commented out lines that users should not be able to select. 
Check that the following lines are hidden from user view when selecting lines in Florence:
- `ShortDashDotDot`
- `Longdashdot`
- `Longdashdotdot`
Anyone but me.
> hide from user view

- src/app/views/login/SignInController.jsx
Note this code isn't actually in use yet.
Errors were not reading the body of the error but instead trying to read 'errors' of the error. This property can be found in the body. This PR should resolve that nesting issue.
Backend is not hooked up so not easy to reproduce but if you provide the wrong log int credentials then in src/app/views/login/SignInController.jsx around  line 85 add: 
```JavaScript
error = { status: 400, body: { errors: [{ code: "InvalidEmail" }] } };
```
You then click Sign in, on the Florence login page, you should see validation error.
> Fix for validation errors not reading the body on API response

- src/app/views/login/SignInController.jsx
Validation rules for dp-identity-api are between 400-499
Zebedee however uses 417 to say 'hey, you need to change your password' on login request.
Whilst feature flag is enabled, people are unable to create new users as they will be unable to login as new users need to change password on first login. In develop we need to have this feature flag turned on to get regular PO sign off as the whole of team 404 is working on auth work; so toggling the feature flag is impractacle. As other teams outside of dev team use Florence on the dev environment they are no unable to create new users on it. So this is a small solution to enable that flow of new user creation to continue. 
They will still get a toast saying "Unexpected error" and they will still get a validation error heading "Fix the …
> A temperary addition to the sign-in-controller

- service/directors.go
- service/directors_test.go
- service/service.go
- src/app/config/reducer.js
- src/app/utilities/api-clients/user.js
- src/app/utilities/http-methods/request.js
- src/app/utilities/http.js
Although the dp-api-router needs to be updated for this to work
- Fix bug where on cookie delete on sign out - if two requests 
- Fix bug that notifications would be deleted if user was signed out as it would set the state to initial state, which means notification array was set to empty immediately after adding a sign out notification error
- Http-requester now allows headers to be set
Bug still present but not part of this PR but now visible due to fixing other bugs (note not a functional issue just visual annoyance) if Florence sends two API requests at once and the users auth token has been removed then these requests will both return errored (401) however they both will sign the user out so you get double notifications saying this has happened - raising a card in the backlog around …
> Hook up Sign Out

- src/app/views/login/SignInForm.jsx
- src/index.js
Florence's new Sign-in screen has a new link "Forgotten your password" which takes the user to `/florence/forgotten-password`. The page it takes you to, does not yet exist, but, will be created in future work.
The 404 Florence page used to say "Sorry, this page couldn't be found" the 'couldnt' was bugging me so added an apostrophe so it now read "couldn't"
Took the branch from master rather than develop, but there are no code changes that are different
Run Florence, there should be no link on the screen for "Forgotten your password?" on the sign-in screen.
Run Florence again but this time add the feature flag `ENABLE_NEW_SIGN_IN=true` then go to the sign-in screen. There should be a link above the Sign-in button saying "Forgotten your password".
Test tabbing, there should be a yellow box …
> Forgot password link added to Sign in screen

- Makefile
The node step of the build was completing before the asset was generated meaning the next step to generate go assets wasn't including it.
Introduced a sleep to allow time for the asset to complete.
Ensure it builds OK on develop.
Anyone but me
> Workaround for race issue with generating main.min.css

- Makefile
- ci/scripts/build.sh
Changed the workaround from #548 to wait for `main.min.css` to have been written.
Also lists files in `/dist/` that will be included in go assets before generating to make debugging the CI job easier.
Check it builds and runs in CI.
Anyone but me.
> Better workaround for race issue with generating main.min.css

- src/app/components/panel/Panel.jsx
- src/app/utilities/errorCodes.js
- src/app/views/change-password/changePasswordConfirmed.jsx
- src/app/views/forgotten-password/forgottenPasswordController.jsx
- src/app/views/forgotten-password/forgottenPasswordController.test.js
- src/app/views/forgotten-password/forgottenPasswordEmailSent.jsx
- src/app/views/forgotten-password/forgottenPasswordRequest.jsx
- src/app/views/login/SignInController.jsx
- src/app/views/login/SignInController.test.js
- src/app/views/login/SignInForm.jsx
- src/scss/base/_variables.scss
When a user submits a password reset and is successful, they will be directed to this new screen
Panel component in some cases was being misused and propTypes not matching. These have now been resolved
prop 'heading' was being misspelt, this has now been corrected.
Make sure you are running the `dp-identity-api` - note you don't need any user accounts to test this PR
Run Florence with the feature flag `ENABLE_NEW_SIGN_IN=true` If pulling this PR for the first time you will need to run `make node-modules` before running the `make debug` command (`make node-modules` will rebuild the JS/React side of Florence).
Navigate to http://localhost:8081/florence/forgotten-password and have a play around with the screen. 
It is important to note that we do not provide detail as to which emails are …
> Forgotten Password request submitted screen

- src/app/views/datasets-new/create/CreateCantabularDatasetController.jsx
- src/app/views/datasets-new/create/CreateCantabularDatasetController.test.js
- src/app/views/datasets-new/create/CreateDatasetController.jsx
- src/app/views/datasets-new/create/CreateDatasetController.test.js
- src/index.js
- src/package-lock.json
- Amended route for Cantabular datasets
- Created new controller to handler Cantabular types with different POST body to non-Cantabular types
- Amended/added unit tests
- Updated `node-fetch` version
- Check unit tests pass
- Sanity check
Run these services:
- dp-frontend-dataset-controller `make debug ENABLE_CENSUS_PAGES=true`
- florence - use this branch 
- sixteens
- dp-frontend-router
- dp-publishing-dataset-controller
- dp-api-router
- dp-compose/cantabular-import
- **N.B.** There are a number of services that are run via this subfolder of dp-compose
Step:
1. POST a cantabular recipe using Postman 
You'll need to update the headers to include your `X-Florence-Token` and send this example recipe (feel free to change to experiment)
```json
{
"alias": "Some Cantabular", …
```
> Add format to dataset POST for Cantabular types 

- src/app/components/validate-new-password/NewPasswordInput.jsx
- src/app/views/forgotten-password/setForgottenPasswordController.jsx
Validation for the forgotten password is being triggered before the state change. As such it actually validates the password minus the last character entered. This resolved that
- in addition, there is an error in the console about a required prop, but the prop is never used so has been removed.
Pull the PR Run Florence with the feature flag `ENABLE_NEW_SIGN_IN=true`
Go to http://localhost:8081/florence/password-reset
Type in the password field, does it respond as expected (Now after a single lowercase character does it show a tick in the 'at least 1 lowercase character required' validation field
(Note submit won't work unless you create an account in Cognito)
> Call validation check after password has been updated

- src/app/utilities/http-methods/request.js
- src/app/views/datasets-new/edit-metadata/DatasetMetadata.jsx
There are few errors in this component and this PR is solving them 
check if you are able to create datasets correctly 
If you go to florence and log in, create a new collection (enter a name, choose manual publish and create), then choose create/edit content from the frame that comes up, choose filterable dataset and choose one from the list ('cantabular working' works), on the next page when you go to select a version (version 2 in this case) you'll be shown a blank page instead of the next step in the journey (edit metadata)
> bug: DatasetMetadata - fix errors in props

- src/app/views/users/change-password/ChangeUserPasswordController.jsx
- src/app/views/users/change-password/ChangeUserPasswordController.test.js
Ticket:  [[BUG] User can't change password in Florence](https://trello.com/c/SlGAppNd/594-bug-user-cant-change-password-in-florence)
When user resets a password in Florence is getting a blank screen instead of Change password modal.
Log in to Florence
Go to Users and access
Click Change password button and you should be able to see the Modal Change password
all
> Bug: Password change state reference error

- src/app/views/datasets-new/edit-metadata/DatasetMetadata.jsx
This bug was reported to support team. 
[Ticket](https://trello.com/c/THhQiWWY/597-bug-florence-metadata-missing-contact-name)
Details of request:On the metadata page, the option to amend the contact name has disappeared and been replaced by a duplicated National Statistics radio button. It's appearing on every dataset. 
> bug: add back contact name in datasets edit view

- src/app/components/dynamic-list/DynamicListItem.jsx
- src/app/views/collections/CollectionsController.jsx
- src/app/views/collections/create/CollectionCreateController.jsx
- src/app/views/collections/mapper/collectionMapper.js
- src/app/views/collections/mapper/collectionMapper.test.js
[Ticket](https://trello.com/c/PxfpfRHw/562-show-correct-lasteditdate-on-collection-screen)
Made changes to the code to show properly  **last edited** in the page of collections:  email of the person who edited and the date stamp. The events array comes already sorted so I used `pop()` which is the quickest way to get the last element form the array. 
Current code was **always** showing the first event, when the change in collection page has been created not edited and not the latest. 
check code and reach out if you need demo 
front end devs
> bug: Florence Collections Details - Last edited page data was wrong

- src/app/constants/Errors.js
- src/app/views/collections/create/CollectionCreate.jsx
- src/app/views/collections/create/CollectionCreateController.jsx
- src/app/views/collections/create/CollectionCreateController.test.js
- src/app/views/collections/create/__snapshots__/CollectionCreateController.test.js.snap
- src/app/views/collections/edit/CollectionEdit.jsx
- src/app/views/collections/edit/CollectionEditController.jsx
- src/app/views/collections/validation/collectionValidation.js
- src/app/views/collections/validation/collectionValidation.test.js
After testing the changes made to name validation it was brought to my attention users expect the validation to happen on submit more then on blur. I also decided to refactor now the feature to fit the user customs. 
I added name validation to existing validation class and added test for this addition. 
please verify the code and tests
> Collection Name Validation

- src/app/components/banner/Banner.jsx
- src/app/components/banner/Form.jsx
- src/scss/components/_banner.scss
Corrections after testing:
- add description value on edit
- make uri part of link not separate 
-add default value
> fix: add missed description and correct link

- src/app/components/banner/Banner.test.js
This quick and simple  PR is addition to the feature Emergency banner.
I noticed few functionality wasn't tested so I expanded  tests slightly so now newly created component has 100% coverage. 
(I left out the elements which were reused to put on the list of tech debt to fill in when time permitted as those components will be refactored later on.)
> Feature - Emergency banner,  expand test for 100% coverage

- src/app/views/datasets-new/create/CreateCantabularDatasetController.jsx
- src/app/views/datasets-new/create/CreateCantabularDatasetController.test.js
- src/app/views/datasets-new/create/CreateDatasetController.jsx
- src/app/views/datasets-new/create/CreateDatasetController.test.js
- src/app/views/uploads/dataset/upload-details/DatasetUploadMetadata.jsx
- src/index.js
- Updated POST /datasets body to
```
is_based_on: {
id: this.state.isBasedOn,
type: this.state.format,
},
type: this.state.format,
```
- Changed conditionals to look for 'includes' `cantabular` rather than being specific types
- Refactored `CreateCantabularDatasetController` to perform a GET instead of relying on query string parameters 
- Updated unit tests
- Sense check
- Tests pass
Anyone but me
> Feature/update post body for Cantabular types

- README.md
- config/config.go
- config/config_test.go
The `ENABLE_DATASET_IMPORT` feature flag is ON in production and development, and it has been like that for years. However locally we still rely on setting an environment variable, which sometimes causes confusion: different behaviour on environments than locally.
There is even [documentation](https://github.com/ONSdigital/dp/blob/main/guides/INSTALLING.md#running-the-apps) to set this variable when running it locally (this will be updated)
Ideally we'll need to tidy up this flag but just setting it to true for now so that devs don't need to do anything special for Florence to behave like prod. 
Check changes make sense.
Anyone
> Enable dataset import by default

- src/app/components/back-button/BackButton.jsx
- src/app/components/selected-items/SelectedItemList.jsx
- src/app/config/selectors.js
- src/app/config/thunks.js
- src/app/utilities/api-clients/user.js
- src/app/views/users/UsersList.jsx
- src/app/views/users/UsersList.test.js
- src/app/views/users/edit/EditUser.jsx
- src/app/views/users/edit/EditUser.test.jsx
- src/app/views/users/groups/AddGroupsToUser.jsx
- src/app/views/users/groups/AddGroupsToUser.test.jsx
- src/app/views/users/index.jsx
Ticket [#883: Add filters to user list screen to allow viewing of deactivated users](https://trello.com/c/1VgBC5H2/883-883-add-filters-to-user-list-screen-to-allow-viewing-of-deactivated-users)
Plus missed commits for last PR:
- apply  lint correction for last PR
- don't show user notification about changes when submitting form 
> feature: add ability to filter users

- config/config.go
- config/config_test.go
- service/directors.go
- service/directors_test.go
- service/service.go
- src/legacy/js/functions/_tags.js
Make calls to the topics api via the api router.
Also remove duplication of `topics` in the url
Having the `api-router` (with `ENABLE_TOPIC_API` flag set to true) and `dp-topic-api` (with data in the relevant collection) running :
Create/edit an article and navigate to the tags widget: the topic and subtopic dropdowns will be populated
Any dev
> Call topics api via api router

- src/app/components/chip/Chip.jsx
- src/app/components/table/Row.jsx
- src/app/components/table/Table.jsx
- src/app/views/users/edit/EditUser.jsx
- src/app/views/users/edit/__snapshots__/EditUser.test.jsx.snap
- src/app/views/users/groups/AddGroupsToUser.jsx
- src/app/views/users/groups/AddGroupsToUser.test.jsx
- src/app/views/users/groups/User.jsx
- src/app/views/users/groups/UserGroupsList.jsx
- src/app/views/users/groups/__snapshots__/AddGroupsToUser.test.jsx.snap
- src/scss/components/_table.scss
Ticket: [#741: View list of groups for user from user details screen](https://trello.com/c/Wt8KGtRL/741-741-view-list-of-groups-for-user-from-user-details-screen)
Also correcting the bug on user edit screen when user submitting changes.
@dandwal
> 741 show list of groups styled as per its role

- src/app/components/simple-selectable-list/SimpleSelectableList.jsx
- src/app/config/groups/thunks.js
- src/app/config/thunks.js
- src/app/utilities/errorCodes.js
- src/app/views/groups/__snapshots__/Groups.test.jsx.snap
- src/app/views/users/UsersList.jsx
[Feature 908: Users and teams screens not displaying errors when getting 5xx ](https://trello.com/c/mqiR1Dmh/908-908-users-and-teams-screens-not-displaying-errors-when-getting-5xx-errors-from-identity-api)
code
> feature/908 - add errors handling

- src/app/utilities/api-clients/teams.js
- src/app/views/collections/create/CreateNewCollection.jsx
Ticket: [Bug/ unable to add team to collection](https://trello.com/c/z1G8RkIm/926-unable-to-add-a-team-to-a-new-collection)
Fix bug created when mapping the groups was removed. 
The change is for old legacy auth so those views will be removed soon.
My solution for this bug is to change the comparison operator to compare values but do not type as old api returns id as a numbers but javascript always sends values in events as a string. 
I also spotted bug on api call so corrected this as well.
before:
devs
> Bug/ unable to add team to collection

- src/app/views/uploads/dataset/upload-details/DatasetUploadDetails.jsx
Small fix to the instantiation of the `fileURL` variable. This variable is provided with the path based on whether the new or old upload system is being used.  This value is then passed to the import services
Sense check the change
Anyone
> fix file URL in DatasetUploadDetails to work between feature toggled upload systems

- src/app/components/navbar/NavBar.jsx
- src/app/components/navbar/NavBar.test.js
- src/app/components/navbar/index.jsx
[BUG: #899: Security tab being shown when feature flag is off](https://trello.com/c/pcwDM8YV/899-899-security-tab-being-shown-when-feature-flag-is-off
)
additionally in this PR:
- linting correction
- remove duplication of `Interactives` link and move it out of the User / Teams block
FLAG enablePermissionsAPI ON 
--------------------------
FLAG enablePermissionsAPI OFF
>  #899: Security tab being shown when feature flag is off

- src/app/components/navbar/NavBar.jsx
- src/app/components/navbar/NavBar.test.js
- src/app/components/navbar/index.jsx
- src/app/config/selectors.js
- src/app/config/thunks.js
- src/app/utilities/api-clients/collections.js
- src/app/views/collections/edit/CollectionEditController.jsx
- src/app/views/collections/edit/CollectionEditController.test.js
- src/app/views/groups/edit/index.jsx
- src/package-lock.json
This PR is the update for new auth functionality: 
1. Bug - when creating police pass groups id not collection
2. show list of new groups in Collection Edit when NewSignIn flag is on
3. When creating policy use put so policy id is the same as collection id
4. create api calls
5. include action when editing user as was not included 
6. #945: Users tab should only be visible to admins
> New Auth - corrections

- src/app/utilities/auth.js
- src/legacy/js/classes/florence.js
Unable to access legacy florence screens when logged in with JWT sessions (returned to login screen).
If florence is using the new login strategy (make debug ENCRYPTION_DISABLED=true ENABLE_PERMISSION_API=true ENABLE_NEW_SIGN_IN=True) then authenticate via local storage otherwise it should grab the cookie.
Option 1:
Log into Florence as admin or publisher
Click on a collection
Click Create/Edit content button
Click Old Workspace
Option 2:
Log into Florence as admin or publisher
Click on the Publishing Queue tab
anyone
myself
> #951: Accessing legacy florence logs user out with JWT sessions

- src/app/components/layout/Layout.jsx
- src/app/components/layout/index.jsx
- src/app/utilities/api-clients/user.js
- src/app/utilities/auth.js
- src/index.js
Interactive screens doesnt refresh
The auth can check the state or if we have a token. the reason for this is that the state should have been passed top down , all the auth should have been set in the top level and then passed down through the router. But as we are removing the current auth then this is not an issue in the new auth. We could use context api to pass the state back up to the connected router.
pull the code down and run with interactive flags
anyone
myself
> fixes interactive auth

- src/legacy/js/functions/_t16ReleaseEditor.js
- src/legacy/js/functions/_t4ArticleDownloadEditor.js
- src/legacy/js/functions/_t4ArticleEditor.js
- src/legacy/js/functions/_t4BulletinEditor.js
- src/legacy/js/functions/_t5TimeseriesEditor.js
- src/legacy/js/functions/_t6CompendiumChapterEditor.js
- src/legacy/js/functions/_t6CompendiumDataEditor.js
- src/legacy/js/functions/_t6CompendiumEditor.js
- src/legacy/js/functions/_t7QmiEditor.js
- src/legacy/js/functions/_t8LandingPageEditor.js
- src/legacy/templates/workEditT16.handlebars
- src/legacy/templates/workEditT4Article.handlebars
- src/legacy/templates/workEditT4Bulletin.handlebars
- src/legacy/templates/workEditT8LandingPage.handlebars
Checkbox handling is being done differently across files and this PR will make them consistent.
- Handlebar templates will not including the checked attribute
- Js will add the checked prop using a generic `checkBoxStatus` function with the relevant field
- Js will refer to checkboxes by id rather than wider selectors
Check code makes sense. Test check boxes retain the value for different page type
Anyone
> Unify checkbox handling

- src/app/views/groups/edit/EditGroup.jsx
Fixes Error when trying to edit an existing group to add or remove team members.
Run the florence `ENABLE_PERMISSION_API=true`
1. Login as Admin.
2. Preview Teams tab.
3. select an existing  preview team
4. remove a member from the team and/or select a member to add to the team
6. Open network tab of the dev tools
7. Create Team button
anyone
myself
> Fixes #981: Edit team/group error trying to add/remove members

- src/app/config/reducer.js
If you switch from the Preview Teams page to Team detail page it duplicates the list of members each time.
To fix this i have fixed a bug in the members reducer.
Run Florence with `ENABLE_NEW_SIGN_IN=true`
Goto http://localhost:8081/florence/groups
click on a group
Either use the browser back button or click the Back link
Click on the same group again
You should now see the duplicated members
Repeat & each time will duplicate another line of members
Florence devs
myself
> Fixes #976: Navigate from Preview Teams to group renders duplicate users

- src/app/components/back-button/BackButton.jsx
- src/app/utilities/redirect.js
- src/app/views/groups/Groups.jsx
- src/app/views/groups/Groups.test.jsx
- src/app/views/groups/__snapshots__/Groups.test.jsx.snap
- src/app/views/login/LoginController.jsx
- src/app/views/login/LoginController.test.js
- src/app/views/login/SignIn.jsx
- src/app/views/login/SignIn.test.js
- src/app/views/security/Security.jsx
- src/app/views/security/__snapshots__/Security.test.jsx.snap
- src/app/views/users/UsersList.jsx
- src/app/views/users/UsersList.test.js
- src/package.json
Back button doesn't implement the History API
The back buttons for groups & users doesn't implement the History API correctly, these fixes enable to user to navigate to the previous pages.
Check that these routes are correct and if im missing any others...
- Click on Users and access tab
- Click on Preview teams
- Click "back" button
florence devs
myself
> Fixes #978: Back button doesn't implement the History API

- src/legacy/package-lock.json
- src/package-lock.json
- src/package.json
Upgrade some dev dependencies to remove 40 vulnerabilities flagged by `npm audit`.
Note our audit job runs `npx auditjs ossi` with no issues, but `npm audit` is run as part of the build.
This will fix some of the [dependabots alerts](https://github.com/ONSdigital/florence/security/dependabot)
Check tests pass and Florence runs correctly
Anyone
> Upgrade dev dependencies

- src/app/views/collections/edit/CollectionEditController.jsx
When editing scheduled collection time was reset to morning. 
Fix it by using 24h format to set the publish time
https://trello.com/c/TVPszylu/2404-s2-afternoon-publish-date-time-is-reset-to-morning-on-collection-edit
- click on a collection
- schedule an afternoon publish time (e.g. 2PM)
- save
- go back in to edit, note that the time stays as afternoon (e.g. 14:00)
Frontend devs
> Use 24h format for publish time

- src/app/components/preview-nav/PreviewNav.jsx
Currently broken and not clear for multiple interactives:
> Fix preview dropdown for Interactives

- src/legacy/scss/components/_page.scss
Adds the styling for rendering content in publishDetails page. Currently looks like:
Sanity check Im adding in correct place
Anyone
> Add legacy interactive css content

- src/package.json
This is a duplicate of #821 that was approved by @gilesburdett. I've renamed the branch to follow GitFlow naming convention assuming this was the reason of declined merge.
Fixed `watch-refactored` so `make watch-src` works as intended and rebuilds the files with changes.
I really wanted to add HMR or at least LiveReload in there but it doesn't seem that we actually use the webpack development server in serve mode, likely due to the convoluted structure and port mappings. There seems to be leftovers from webpack v4 config in there but that's a whole different story: there's a lot in there that could do with a solid cleanup, but this must suffice for now.
0. Fire up `florence`
1.  Run `make watch-src`
2. Edit a legacy / old workspace file, refresh, see rebuilt changes
3. Edit a refactored / …
> Fix `make watch-src`

- src/app/utilities/sessionManagement.js
- Remove the "Your session will expire" pop up as isn't adding value ✅ 
- Pop up isn't adding any user value since their session isn't actually about to expire it is just the access token that is ✅ 
- What needs changing:
* Remove last interaction/active timer (3 below) in session refresh login in Florence ✅ 
* Update the "auth state" with the new access token expiry time ✅ 
* Replace current session refresh logic (incl. the popup it produces) with logic that just before access token expiry (maybe 1 min before) based on access token expiry timer (1 below), refresh the access token (i.e. `PUT /api/v1/tokens/self`) and then reset timer ✅ 
Check the code does meets the above expectations
Forence devs …
> #983: Remove access token expiry pop-up

- config/config.go
- config/config_test.go
- service/service.go
Update `Florence` to call the `cantabular metadata extractor api` via the `dp-api-router`.
Read the code, run the tests and go through the Cantabular dataset journey. When running florence don't forget to set the  feature flag to true with `export ENABLE_CANTABULAR_JOURNEY=true && make debug`. To run the `dp-api-router` with the latest changes check out on `feature/add-dp-cantabular-metadata-extractor-api-routing` branch and run `export ENABLE_CANTABULAR_METADATA_EXTRACTOR_API=true && make debug`
Anyone
> Call cantabular metadata extractor via api router

- src/app/views/collections/details/CollectionDetailsController.jsx
- src/app/views/collections/details/CollectionDetailsController.test.js
- src/app/views/workflow-preview/WorkflowPreview.jsx
Fixes two bugs which meant users were being redirected to the Edit Cantabular metadata screen despite enableCantabularMetadata feature flag being set to false.
Ensure feature flag is set to false (export ENABLE_CANTABULAR_JOURNEY=false) & run Cantabular dataset journey.  Also run test suite.
Anyone
> adds feature flag to back button and collection details routing

- src/app/config/user/userHooks.js
- src/app/views/login/SignIn.jsx
- src/app/views/new-password/changePasswordConfirmed.jsx
- src/app/views/new-password/forgottenPasswordController.jsx
When a new user logins in the first time, they are asked to change their temp password, then a button is displayed to inform the user that they can start using Florence. When they click this button they are signed in. We dont want them to be signed in like this, rather redirect them back to the login screen.
Also added a fix that blows up a page.
read through the changes, and if necessary ask for a demo
anyone
myself & Geoff
> Fixes login for new user password change

- src/app/utilities/auth.js
- src/app/views/collections/Collections.jsx
- src/app/views/collections/Collections.test.js
When a user is logged in as a VIEWER & refreshes the page on the collections screen , their is a request to fetch the groups but viewers do not have permission to view groups
ask for a demo
anyone
myself
> #1003: Viewer collections page reload causes sign out / session expired

- src/app/components/navbar/NavBar.jsx
publisher should not see Users tab
- login as publisher
- see Users&access tab (should not see this)
- click Reports (can now see Team - should not see this)
- should not see those tabs
anyone
myself
> #993: publisher should not see Users tab

- service/handlers.go
- service/service.go
- src/app/utilities/api-clients/user.js
Toggling between the new login and the old login fails due to to existence of the tokens.
1. Enable the JWT sessions (zebedee) and new sign in (florence) feature flags
2. Login
3. Disable the two above feature flags
4. Attempt to log in again
Anyone
myself
> 925: Login fails after going from new login to old login

- src/audit-allowlist.json
Several libraries appear locked to node-fetch@2 & cannot bump to node-fetch@3.2.10
> fixes node-fetch audit fail

- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
Once the cantabular dataset metadata is saved the `Add a dataset` and `Add a publications` links are not responding so the user can't add a new dataset or a new publication to the dataset ([trello ticket](https://trello.com/c/42KPQ9KW/1266-related-links-section-on-edit-metadata-cantabular-screen-cant-be-accessed)).
Run the code, run through Cantabular metadata journey, save, refresh the page and then click on `Add a dataset` and `Add a publications` from the `Related links section` and check if the below window comes up . 
Also don't forget to run the test suite.
Anyone
> Fixes bug on the Related Links section of the Edit Metadata (Cantabular) screen

- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadata.jsx
- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.test.js
- src/app/views/datasets-new/edit-metadata/EditMetadataItem.jsx
Adds related content field to the Edit Metadata (Cantabular) form ([trello ticket](https://trello.com/c/dOW0n2iJ/1248-related-content)).
Run the code, go through Cantabular metadata journey, add data to the `Related content` pop out, save, refresh the page, then go back and edit/delete the related content data you added and also make sure you can complete the journey and publish the dataset . Don't forget to run the test suite.
Anyone
> Adds related content field to the Edit Metadata (Cantabular) form

- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadata.jsx
- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.test.js
- src/scss/elements/_lists.scss
Adds quality statement fields to every dimension of the dataset on the  Edit Metadata (Cantabular) screen ([see trello ticket](https://trello.com/c/38rHCrB1/1287-quality-statement)).
Run the code, go through Cantabular metadata journey,  save, refresh the page and check if the data persists. Don't forget to run the test suite.
Anyone
> Adds quality statement fields to Edit Metadata (Cantabular) screen

- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.test.js
Simplifies title field for Cantabular datasets, using only label rather than concatenating name (i.e. dataset code) + label. As requested by outputs.
Check tests pass, sense check.
Anyone
> reverts Cantabular dataset title to just label field

- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.test.js
Removes preview button from refresh cantabular metadata screen ([trello ticket](https://trello.com/c/P1KQTqn1/1338-refresh-metadata-preview)).
Run the code, go through Cantabular metadata journey and at the end only click `Save` to keep the collection `inProgress`. To test the feature you can either go and manually change some of the dataset fields in mongo(from the mongo `datasets` collection you can manually change `title`,`description`,`keywords` etc and from the `instances` mongo collection you can manually change from the `dimensions` field `label`,`description`,`quality_statement_text` etc) or you can go and manually update/hard-code the `dp-cantabular-metadata-extractor-api` response.
If you, for example, go into mongo and manually change the contact name, when you go on the Edit …
> Removes preview button from refresh cantabular metadata screen 

- src/app/views/workflow-preview/WorkflowPreview.jsx
Removes what looks like a footer and the continue button from the preview dataset landing page ([trello ticket](https://trello.com/c/ZeCrYleS/1345-preview-screen-removal-of-continue-button) ) only for cantabular metadata journey.
Run the code, go through Cantabular metadata journey and check the preview dataset landing page.
1. Before:
2.After:
Anyone
> Removes continue button from preview dataset landing page (cantabular metadata journey)

- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
Fixes [No title saved bug](https://trello.com/c/miEOFwcK/1347-bug-whats-changed-metadata-field). 
The `What's changed?` metadata field is defined in the dataset-api models as being a list of objects with the following properties : `description`, `name` and `type`, but currently the only property which gets sent through from florence in the put request body is the `description`. This change updates the code to send through also the `name`(title) .
Read the code, check the tests pass, run the journey locally add an entry for the `What's changed?` metadata field,save, refresh the page and make sure that the title is still coming through.
Anyone
> Fixes no title saved bug on the What's changed? cantabular metadata field

- Dockerfile
- Dockerfile.concourse
- Makefile
- reflex
- src/legacy/package-lock.json
- src/package-lock.json
- src/package.json
- [Trello card](https://trello.com/c/S2KyzIGX/1024-create-census-hub-stack-using-docker)
- Automatically generate assets on make debug-run
- Configure reflex to ignore changes on `assets` folder
- Upgraded json5 library to version 2.2.2 to fix vulnerability detected by `make audit`
- Make sure changes are ok
- You may run the dp-compose stack using [the branch for this PR](https://github.com/ONSdigital/dp-compose/pull/123)\
- Make sure the upgrade is fine
Anyone
> generate assets on make debug-run and reflex to ignore assets folder

- src/app/views/collections/details/CollectionDetailsController.jsx
- src/app/views/collections/details/CollectionDetailsController.test.js
- src/app/views/datasets-new/versions/DatasetVersionsController.jsx
- src/app/views/datasets-new/versions/DatasetVersionsController.test.js
- src/app/views/workflow-preview/WorkflowPreview.jsx
Includes the dataset multivariate type in the cantabular metadata journey ([Multivariate type added](https://trello.com/c/8RJ1wUYE/1379-multivariate-type-added)).
Read the code, check the tests pass, run the journey locally and make sure to use a recipe which has a `cantabular_multivariate_table` format to check if after creating a dataset you are redirected  to the `Edit metadata (Cantabular)` form and not to the CMD `Edit metadata` form. Also test that the `back` button on the preview screen and the `Edit` button on the collection details screen takes you back to the  `Edit metadata (Cantabular)` form.
1. `back` button on the preview screen
2.  `Edit` button on the collection details screen
Anyone
> Checks for multivariate dataset type - ticket#1379

- src/audit-allowlist.json
`core-js@2.6.12` is a dependency of  `dp-table-builder-ui` library and at the time of writing the current used version of the `dp-table-builder-ui` is `v1.1.1` which is also the latest version and does not address the current vulnerability. So until this gets fixed the vulnerability has been added to the audit allowlist. 
Sense check
Anyone
> Task/audit fix core-js

- src/app/views/collections/details/CollectionDetailsController.jsx
- src/app/views/collections/details/CollectionDetailsController.test.js
- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.test.js
- src/app/views/datasets-new/versions/DatasetVersionsController.jsx
- src/app/views/datasets-new/versions/DatasetVersionsController.test.js
- src/app/views/workflow-preview/WorkflowPreview.jsx
This PR fixes multiple issues on cantabular metadata journey.
1. Handles the error returned by the `dataset-api` when trying to retrieve the dataset type (ticket#1428): 
If the cantabular metadata journey is enabled the dataset type has to be checked to either redirect the user to  the cantabular metadata journey or to the CMD one. To check the type, the `dataset-api` gets called and now, with the changes in this PR, if an error is returned that error is handled, the user is alerted and the journey is stopped (the existing behaviour is to redirect the user by default to the CMD journey even if an error was returned when trying to retrieve the dataset type from the `dataset-api` and there is no message displaying on the screen telling the user about the error) . 
2. Handles the errors …
> Handles the errors returned by the dataset-api & cantabular-metadata-extractor-api services

- src/webpack.config.js
Remove `url-loader` module. From the docs: 
> url-loader lets you import arbitrary files, like images. If you import a .png file, url-loader will ensure that import resolves to a Base64 string representing the contents of the file.
When we use `url-loader` the assets seem broken and don't load properly in browsers. Removed this for now as attempted fixes didn't work and this is depreciated as of v5 so maybe worth moving away from it anyways
Before fix:
After fix:
Anyone
> Fix asset loading/resolving

- src/app/utilities/sessionManagement.js
- src/app/utilities/sessionManagement.test.js
If you deeplink to a page in florence, e.g. /florence/users, and you haven't signed in it tries to redirect you to the login, but there is no session expiry time. This causes a NaN error leading to a white screen. 
Run Florence.
Go to /florence/users without signing in
Observe how it redirects you to the login screen
React/JS Dev.
> Stop whitescreen on no session expiry

- src/legacy/js/functions/_viewController.js
Fix "Preview teams" navbar tab logic so that it goes to `/groups` OR `/teams` depending on feature flag
Anyone
> Fix "Preview teams" navbar tab logic

- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.jsx
- src/app/views/datasets-new/edit-metadata-cantabular/CantabularMetadataController.test.js
- src/legacy/js/functions/_tags.js
- src/legacy/package-lock.json
- src/package-lock.json
- src/package.json
Add check for if no subtopics (introduced by new parent topics without subtopics)
Check code good, tests pass. 
Optionally:
Run Florence locally with SecAuth on, port forward to api router in sandbox. 
Create collection, edit bulletin page (or other with tags). Observe tagging now works appropriately. 
Florence dev.
> Account for topics with no subtopics

- src/app/utilities/api-clients/user.js
- src/legacy/js/functions/_logout.js
Stopped JS trying to remove access_token as HttpOnly. Clears errors and ensures tokens removed on logout. 
Run Florence in NewSignIn mode and port forward to sandbox api router. 
Sign in, observe cookies, sign out. Check access_token is gone. Do the same from old Florence too. 
Florence dev.
> Fix removal of access_token cookie

- src/app/utilities/api-clients/user.js
- src/legacy/js/functions/_logout.js
Removed warnings and console errors for unauthenticated timeout.
Port forward to api router in sandbox publishing.
Run florence with enableNewSignIn: true
Login
Wait for 1h16m ensuring your tunnel remains open.
Click a button in Florence.
Observe logout now doesn't throw hundreds of errors.
Florence dev.
> Remove warnings for unauthenticated signout

- Makefile
- README.md
Add nvm to makefile targets to remove the need to remember to run `nvm use` everytime you switch to the repo. This also makes it quicker and easier to switch between working on different applications with differing node version.
Update the readme to highlight the steps to install nvm.
Ensure all make targets work correctly and that the correct node version is used (nvm outputs version used to stdout).
Review the README changes.
!me
> Add nvm to makefile targets

- src/app/utilities/notifications.js
Fixed issue with notifications class being overridden, causing them not to be able to dismiss. 
Run Florence (`make debug && make watch-src`) - access /florence/collections to trigger notifications. Observe they are now dismissable. 
Not me.
> Fix notification dismiss

- service/service.go
- src/app/utilities/api-clients/images.js
Remove Image API proxy
Check looks ok, tests pass. 
To test:
- Run florence
- Port forward sandbox publishing api router
- Edit homepage in a collection
- Add an image (you won't see the thumbnail due to cross-domain auth issues)
Not me.
> Remove Image API Proxy

- src/legacy/js/zebedee-api/_deleteAPIDatasetFromCollection.js
A recent change introduced a typo in the legacy JS causing publishing-queue to fail
Ensure tests pass and fix looks sensible
Anyone
> Fix typo in legacy JS causing runtime failure
